/**
 * Reading Roblox's documentation repository.
 *
 * The catalogue in `robloxMembers.ts` is generated, so nothing in the shipped
 * build exercises the parser that wrote it — and a parser nothing exercises is
 * one that quietly returns nothing the day the format shifts. "No methods" then
 * looks exactly like "no network", and the catalogue goes empty in a release.
 *
 * So the shape of a class file is written out here as a fixture, with the parts
 * that decide what is kept: a required argument, an optional one, an enum, a
 * yield, a deprecation and a security context.
 */

import { describe, expect, it } from "vitest";

import { firstSentence, methodsOf, parseYaml, pinType } from "../scripts/lib/creatorDocs.js";

const CLASS_FILE = `# This file is automatically generated.
name: TestService
type: class
summary: |
  A service that exists to be parsed.
methods:
  - name: TestService:IsReady
    summary: |
      Returns whether the thing is ready. Everything after the first full stop
      belongs on the reference page rather than in a menu.
    description: |
      Longer prose, which nothing keeps.
    code_samples: []
    parameters: []
    returns:
      - type: boolean
        summary: |
          Whether it is ready.
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Safe
  - name: TestService:Bind
    summary: |
      Binds a function to a key.
    code_samples: []
    parameters:
      - name: key
        type: KeyCode
        default:
        summary: |
          The \`Enum.KeyCode\` to bind.
      - name: priority
        type: int
        default: 2000
        summary: |
          Where in the order it runs.
    returns:
      - type: ()
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
  - name: TestService:LoadAsync
    summary: |
      Fetches the thing.
    parameters: []
    returns:
      - type: Array
        summary: ''
    tags:
      - Yields
    deprecation_message: ''
    security: None
  - name: TestService:OldWay
    summary: |
      The way it used to be done.
    parameters: []
    returns:
      - type: boolean
        summary: ''
    tags:
      - Deprecated
    deprecation_message: |
      Superseded by something else.
    security: None
  - name: TestService:StudioOnly
    summary: |
      Something only a plugin may call.
    parameters: []
    returns:
      - type: ()
        summary: ''
    tags: []
    deprecation_message: ''
    security: PluginSecurity
events:
  - name: TestService.Fired
    summary: |
      Not a method, and not wanted here.
`;

const doc = parseYaml(CLASS_FILE);
const isEnum = (name: string) => name === "KeyCode";
const methods = methodsOf(doc, "TestService", isEnum);
const byName = (name: string) => methods.find((m) => m.name === name);

describe("a class file", () => {
	it("parses into the parts the catalogue keeps", () => {
		expect(doc.name).toBe("TestService");
		expect(doc.methods).toHaveLength(5);
		expect(doc.events).toHaveLength(1);
	});

	it("keeps only what a game script can call", () => {
		expect(methods.map((m) => m.name)).toEqual(["IsReady", "Bind", "LoadAsync"]);
	});

	it("reads a method's signature", () => {
		expect(byName("IsReady")).toMatchObject({
			from: "TestService",
			returns: "boolean",
			params: [],
			pure: true,
		});
	});

	/** A documented default is what says an argument may be left out. */
	it("tells a required argument from an optional one", () => {
		const params = byName("Bind")?.params ?? [];
		expect(params[0]).toMatchObject({ name: "key", type: "string", enum: "KeyCode" });
		expect(params[0].optional).toBeUndefined();
		expect(params[1]).toMatchObject({ name: "priority", type: "number", optional: true });
	});

	it("marks what yields, and never calls it read-only", () => {
		expect(byName("LoadAsync")).toMatchObject({ yields: true, returns: "table" });
		expect(byName("LoadAsync")?.pure).toBeUndefined();
	});

	/** `Bind` gives nothing back, so there is nothing to read it as. */
	it("leaves a method that returns nothing with no return type", () => {
		expect(byName("Bind")?.returns).toBe("");
		expect(byName("Bind")?.pure).toBeUndefined();
	});
});

describe("a summary", () => {
	it("is cut to its first sentence", () => {
		expect(byName("IsReady")?.summary).toBe("Returns whether the thing is ready.");
	});

	it("renders a documentation cross-reference as what it links to", () => {
		expect(firstSentence("Calls `Class.RunService:IsServer()|IsServer()` first."))
			.toBe("Calls `IsServer()` first.");
		expect(firstSentence("Takes an `Enum.KeyCode` value.")).toBe("Takes an `KeyCode` value.");
	});
});

describe("a documented type", () => {
	it("becomes the pin type that means the same thing", () => {
		expect(pinType("int")).toBe("number");
		expect(pinType("float")).toBe("number");
		expect(pinType("User")).toBe("number");
		expect(pinType("bool")).toBe("boolean");
		expect(pinType("Content")).toBe("string");
		expect(pinType("Variant")).toBe("any");
		expect(pinType("Function")).toBe("function");
	});

	/** An engine class or datatype is a pin type already. */
	it("passes the engine's own names through", () => {
		expect(pinType("Player")).toBe("Player");
		expect(pinType("RaycastParams")).toBe("RaycastParams");
	});

	it("collapses the ones Luau has no distinction for", () => {
		expect(pinType("List<Player>")).toBe("table");
		expect(pinType("Dictionary<string, any>")).toBe("table");
		expect(pinType("RaycastResult?")).toBe("RaycastResult");
		expect(pinType("()")).toBe("");
	});
});
