/**
 * The Lune demos, held to the compiler that publishes them.
 *
 * Each demo is a real graph and the page shows the Luau it compiles to, which
 * is only worth anything if the compiling is checked. A demo that stopped
 * compiling — a node renamed, a pin id changed, a Lune signature moving under
 * it when the catalogue is regenerated — would otherwise sit on the site being
 * confidently wrong, and it is the page a Lune developer is most likely to
 * copy from.
 *
 * Warnings are pinned as tightly as errors, in both directions. A demo that
 * starts warning is a demo teaching somebody to write something Roswaal
 * complains about; a demo that *stops* warning where the page says it will
 * means the page is now describing something that no longer happens.
 */

import { describe, expect, it } from "vitest";

import { compile } from "../src/core/compiler/index.js";
import { createRegistry } from "../src/core/nodes/index.js";
import { DEMOS, demoLuau } from "../src/core/docs/demos.js";
import { LUNE_MODULES } from "../src/core/luneApi.js";
import { callOf, moduleOf } from "../src/core/luneCalls.js";
import { isLuneCall } from "../src/core/nodes/lune.js";

const registry = createRegistry();

describe("every Lune demo", () => {
	it("is actually a set of them", () => {
		expect(DEMOS.length).toBeGreaterThanOrEqual(4);
		expect(new Set(DEMOS.map((d) => d.slug)).size).toBe(DEMOS.length);
	});

	it.each(DEMOS)("$slug compiles without an error", (demo) => {
		const result = compile(demo.script(), registry);
		const errors = result.diagnostics.filter((d) => d.severity === "error");
		expect(errors.map((e) => e.message)).toEqual([]);
	});

	it.each(DEMOS)("$slug writes something", (demo) => {
		const luau = demoLuau(demo, registry);
		expect(luau.trim()).not.toBe("");
		// Every one of these prints or exits. A demo that compiled to a file
		// doing nothing observable would still pass everything above.
		expect(luau).toMatch(/print\(|process\.exit\(/);
	});

	it.each(DEMOS)("$slug is a Lune graph", (demo) => {
		expect(demo.script().target).toBe("lune");
	});

	/**
	 * The rule the whole library rests on: a generated file never grows an
	 * import nobody placed. If a demo called into a module it had not declared
	 * the compile would error, so this checks the other direction — that the
	 * requires in the output are exactly the modules the graph declared.
	 */
	it.each(DEMOS)("$slug requires exactly what it declared", (demo) => {
		const script = demo.script();
		const declared = (script.modules ?? []).map((m) => m.specifier).sort();
		const required = [...demoLuau(demo, registry).matchAll(/require\("([^"]+)"\)/g)]
			.map((m) => m[1])
			.sort();
		expect(required).toEqual(declared);
	});

	/** A call has to name a function the catalogue actually has. */
	it.each(DEMOS)("$slug only calls Lune functions that exist", (demo) => {
		const byAlias = new Map(LUNE_MODULES.map((m) => [m.alias, m]));
		for (const node of demo.script().nodes) {
			if (!isLuneCall(node.def)) continue;
			const alias = moduleOf(node.config);
			const call = callOf(node.config);
			const found = byAlias.get(alias)?.functions.some((f) => f.name === call);
			expect([`${alias}.${call}`, found]).toEqual([`${alias}.${call}`, true]);
		}
	});

	/**
	 * The page writes a `warns` note for a demo that raises one on purpose, so
	 * the two have to agree: a warning with no note is a surprise, and a note
	 * with no warning is the page describing something that stopped happening.
	 */
	it.each(DEMOS)("$slug warns exactly where the page says it does", (demo) => {
		const warnings = compile(demo.script(), registry).diagnostics
			.filter((d) => d.severity === "warning");
		if (demo.warns === undefined) {
			expect(warnings.map((w) => w.message)).toEqual([]);
		} else {
			expect(warnings.length).toBeGreaterThan(0);
		}
	});
});

describe("the demos page", () => {
	it("shows the Luau the compiler wrote, header stripped", () => {
		const demo = DEMOS[0];
		const luau = demoLuau(demo, registry);
		expect(luau).not.toMatch(/^--\s*!strict/);
		expect(luau).not.toMatch(/Generated by Roswaal/);
		expect(luau).toContain('require("@lune/fs")');
	});
});
