/**
 * The modules a script writes, and the line that says so.
 *
 * A generated file edited by hand loses the edit the next time the script
 * runs, so each one says in its first line which script writes it, and
 * `.gitattributes` marks it generated. The list here is the list of both: a
 * file that starts saying it is generated and is not listed fails, and so
 * does a listed file that stops saying it.
 */

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Every generated module, and the script that writes it. */
const GENERATED: Record<string, string> = {
	"src/core/docs/demoLayout.gen.ts": "fold-demo-layout.mjs",
	"src/core/docs/robloxDemos.gen.ts": "build-roblox-demos.mjs",
	"src/core/licenceData.ts": "build-licences.mjs",
	"src/core/luneApi.ts": "build-lune.mjs",
	"src/core/robloxData.ts": "build-roblox.mjs",
	"src/core/robloxMembers.ts": "build-members.mjs",
	"src/core/robloxProperties.ts": "build-properties.mjs",
	"src/core/themeData.ts": "build-themes.mjs",
};

/** Generated too, and with no room for a comment. */
const GENERATED_JSON: Record<string, string> = {
	"src/core/robloxEngine.json": "build-engine.mjs",
};

const header = (script: string) => `// Generated by scripts/${script}. Do not edit by hand.`;

function filesUnder(dir: string, out: string[] = []): string[] {
	for (const name of readdirSync(dir)) {
		const path = join(dir, name);
		if (statSync(path).isDirectory()) filesUnder(path, out);
		else out.push(path);
	}
	return out;
}

const scripts = filesUnder(join(ROOT, "scripts"))
	.map((path) => readFileSync(path, "utf8"))
	.join("\n");

describe("generated modules", () => {
	it.each(Object.entries(GENERATED))("%s says which script writes it", (file, script) => {
		const first = readFileSync(join(ROOT, file), "utf8").split(/\r?\n/)[0];
		expect(first).toBe(header(script));
		// And the script writes that line, so regenerating keeps it.
		expect(scripts).toContain(header(script));
	});

	it("lists every module that says it is generated", () => {
		const claiming = filesUnder(join(ROOT, "src"))
			.filter((path) => /\.tsx?$/.test(path))
			.filter((path) => readFileSync(path, "utf8").startsWith("// Generated by"))
			.map((path) => relative(ROOT, path).split("\\").join("/"));
		expect(claiming.sort()).toEqual(Object.keys(GENERATED).sort());
	});

	it.each(Object.entries(GENERATED_JSON))("%s is written by scripts/%s", (file, script) => {
		expect(readFileSync(join(ROOT, "scripts", script), "utf8")).toContain(file);
	});

	it("marks every one of them generated in .gitattributes", () => {
		const files = [...Object.keys(GENERATED), ...Object.keys(GENERATED_JSON)];
		const out = execFileSync("git", ["check-attr", "linguist-generated", "--", ...files], {
			cwd: ROOT,
			encoding: "utf8",
		});
		for (const file of files) expect(out, file).toContain(`${file}: linguist-generated: true`);
	});
});
