/**
 * The Lune demo project, and the page it was generated from.
 *
 * The four programmes exist twice: as pictures on the demos page, and as a
 * project somebody can open. `scripts/build-lune-demo.mjs` writes the second
 * from the first, which only helps if somebody runs it — a graph edited in
 * `demos.ts` and never regenerated leaves the project quietly describing the
 * version before.
 *
 * So the two are compared here. The failure message is the fix: run the script.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { DEMOS } from "../src/core/docs/demos.js";
import { DEMO_PROJECTS, demoFor } from "../src/core/demoProjects.js";
import type { NodeScript } from "../src/core/schema.js";

const root = new URL("../examples/lune-demo/", import.meta.url);

const onDisk = (slug: string): NodeScript =>
	JSON.parse(readFileSync(new URL(`.roswaal/scripts/${slug}.nodescript`, root), "utf8"));

describe("the Lune demo project", () => {
	it("has a project file that says Lune", () => {
		const project = JSON.parse(readFileSync(new URL("roswaal.json", root), "utf8"));
		expect(project.target).toBe("lune");
		// A Lune program has no DataModel, so nothing to hand Rojo.
		expect(project.rojoProject).toBeUndefined();
	});

	/**
	 * Everything except where the nodes sit.
	 *
	 * The project is a project. Somebody will open it, tidy a graph that was
	 * laid out by a rule rather than by eye, and save — and a test that called
	 * that a failure would be a test fighting the tool it ships with. What
	 * must not drift is what the programme *is*: the nodes, what they are
	 * configured to do, what is wired to what, and what it requires.
	 *
	 * The page redraws from its own coordinates either way, so the two can
	 * differ in layout and still be the same four programmes.
	 */
	const meaning = (script: NodeScript) => ({
		...script,
		nodes: script.nodes
			.map(({ x: _x, y: _y, ...rest }) => rest)
			.sort((a, b) => a.id.localeCompare(b.id)),
	});

	it.each(DEMOS)("$slug on disk is the graph the page draws", (demo) => {
		expect(meaning(onDisk(demo.slug))).toEqual(meaning(demo.script()));
	});

	/**
	 * The bug this project found. Every graph the docs builder makes carries
	 * the builder's default id, which is invisible while they are pictures and
	 * fatal as a project: the compiler keys generated files by graph id, so
	 * four graphs sharing one made each compile delete the file before it.
	 */
	it("gives every graph an id of its own", () => {
		const ids = DEMOS.map((d) => d.script().id);
		expect(new Set(ids).size).toBe(ids.length);
		expect(ids).not.toContain("docs-example");
	});

	it("compiles to one Luau file per graph", () => {
		for (const demo of DEMOS) {
			const luau = readFileSync(new URL(`src/${demo.slug}.luau`, root), "utf8");
			expect(luau).toContain("Generated by Roswaal");
			expect(luau).toContain(`roswaal-graph: ${demo.script().id}`);
		}
	});
});

describe("the demo projects offered", () => {
	it("has one per runtime, and both exist on disk", () => {
		expect(DEMO_PROJECTS.length).toBeGreaterThanOrEqual(2);
		for (const one of DEMO_PROJECTS) {
			const project = JSON.parse(
				readFileSync(new URL(`../examples/${one.dir}/roswaal.json`, import.meta.url), "utf8"),
			);
			expect([one.dir, project.target]).toEqual([one.dir, one.target]);
		}
	});

	it("offers a demo for each runtime Roswaal compiles for", () => {
		expect(demoFor("roblox")).toBeDefined();
		expect(demoFor("lune")).toBeDefined();
	});

	it("says how many graphs each holds, so a card need not open one", () => {
		const lune = demoFor("lune");
		expect(lune?.graphs).toBe(DEMOS.length);
	});
});
