/**
 * The Lune demo project, and the page it was generated from.
 *
 * The four programmes exist twice: as pictures on the demos page, and as a
 * project somebody can open. `scripts/build-lune-demo.mjs` writes the second
 * from the first, which only helps if somebody runs it — a graph edited in
 * `demos.ts` and never regenerated leaves the project quietly describing the
 * version before.
 *
 * So the two are compared here. The failure message is the fix: run the script.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { DEMOS } from "../src/core/docs/demos.js";
import { DEMO_PROJECTS, demoFor } from "../src/core/demoProjects.js";
import type { NodeScript } from "../src/core/schema.js";

const root = new URL("../examples/lune-demo/", import.meta.url);

const onDisk = (slug: string): NodeScript =>
	JSON.parse(readFileSync(new URL(`.roswaal/scripts/${slug}.nodescript`, root), "utf8"));

describe("the Lune demo project", () => {
	it("has a project file that says Lune", () => {
		const project = JSON.parse(readFileSync(new URL("roswaal.json", root), "utf8"));
		expect(project.target).toBe("lune");
		// A Lune program has no DataModel, so nothing to hand Rojo.
		expect(project.rojoProject).toBeUndefined();
	});

	/**
	 * Everything, layout included.
	 *
	 * It did not always include it. The project is a project: somebody opens
	 * it, tidies a graph that was placed by a rule rather than by eye, and
	 * saves — and while there was no way to get that arrangement back into the
	 * page, failing here would have been a test fighting the tool it ships
	 * with.
	 *
	 * `scripts/fold-demo-layout.mjs` is that way, so this is a real failure
	 * again, and the fix is to run it. **If this fails after tidying a demo in
	 * the editor, that is what it is telling you.**
	 */
	const meaning = (script: NodeScript) => ({
		...script,
		nodes: [...script.nodes].sort((a, b) => a.id.localeCompare(b.id)),
		// Sorted for the same reason the nodes are. The editor writes links in
		// the order it holds them, which is not the order the builder made
		// them in, and a wire is the same wire wherever it sits in the array.
		// Keyed by what it connects rather than by its own id, which the editor
		// is also free to renumber.
		links: [...script.links]
			.map(({ id: _id, ...rest }) => rest)
			.sort((a, b) =>
				`${a.from.node}.${a.from.pin}>${a.to.node}.${a.to.pin}`
					.localeCompare(`${b.from.node}.${b.from.pin}>${b.to.node}.${b.to.pin}`),
			),
	});

	it.each(DEMOS)("$slug on disk is the graph the page draws", (demo) => {
		expect(meaning(onDisk(demo.slug))).toEqual(meaning(demo.script()));
	});

	/**
	 * The bug this project found. Every graph the docs builder makes carries
	 * the builder's default id, which is invisible while they are pictures and
	 * fatal as a project: the compiler keys generated files by graph id, so
	 * four graphs sharing one made each compile delete the file before it.
	 */
	it("gives every graph an id of its own", () => {
		const ids = DEMOS.map((d) => d.script().id);
		expect(new Set(ids).size).toBe(ids.length);
		expect(ids).not.toContain("docs-example");
	});

	it("compiles to one Luau file per graph", () => {
		for (const demo of DEMOS) {
			const luau = readFileSync(new URL(`src/${demo.slug}.luau`, root), "utf8");
			expect(luau).toContain("Generated by Roswaal");
			expect(luau).toContain(`roswaal-graph: ${demo.script().id}`);
		}
	});
});

describe("the demo projects offered", () => {
	it("has one per runtime, and both exist on disk", () => {
		expect(DEMO_PROJECTS.length).toBeGreaterThanOrEqual(2);
		for (const one of DEMO_PROJECTS) {
			const project = JSON.parse(
				readFileSync(new URL(`../examples/${one.dir}/roswaal.json`, import.meta.url), "utf8"),
			);
			expect([one.dir, project.target]).toEqual([one.dir, one.target]);
		}
	});

	it("offers a demo for each runtime Roswaal compiles for", () => {
		expect(demoFor("roblox")).toBeDefined();
		expect(demoFor("lune")).toBeDefined();
	});

	it("says how many graphs each holds, so a card need not open one", () => {
		const lune = demoFor("lune");
		expect(lune?.graphs).toBe(DEMOS.length);
	});
});
