/**
 * The Luau typechecking mode: what the generated file declares, and what a graph
 * written by an older build turns into.
 *
 * This was a `strict` checkbox until 0.18.1. Two of the three modes are exactly
 * what that checkbox already did, so most of what is worth testing is that the
 * conversion is lossless — a graph that used to emit `--!strict` still does, and
 * one that emitted no mode line still emits none. A migration that quietly
 * turned checking on would show up as a wall of new type errors in somebody's
 * project, from a release that claimed to have added a dropdown.
 */

import { describe, expect, it } from "vitest";

import { compile } from "../src/core/compiler/index.js";
import { migrateScript } from "../src/core/migrate.js";
import { createRegistry } from "../src/core/nodes/index.js";
import { serialiseScript } from "../src/core/compiler/index.js";
import type { NodeScript, TypecheckMode } from "../src/core/schema.js";
import { Builder } from "./helpers.js";

const registry = createRegistry();

/** A graph with one typed variable and one typed function parameter. */
function graph(typecheck: TypecheckMode): NodeScript {
	const b = new Builder();
	b.variable("health", "number", { t: "number", v: 100 });
	const start = b.node("script.begin");
	const print = b.node("debug.print");
	b.link(start, "then", print, "in");
	return b.build({ typecheck });
}

const firstLine = (code: string) => code.split("\n")[0];

describe("the mode line", () => {
	it("writes nothing at all on Default", () => {
		const code = compile(graph("default"), registry).code;
		expect(firstLine(code)).toBe("-- Generated by Roswaal. Do not edit this file directly;");
		expect(code).not.toContain("--!");
	});

	it("writes --!nonstrict", () => {
		expect(firstLine(compile(graph("nonstrict"), registry).code)).toBe("--!nonstrict");
	});

	it("writes --!strict", () => {
		expect(firstLine(compile(graph("strict"), registry).code)).toBe("--!strict");
	});
});

/**
 * Annotations follow the mode line rather than `strict` alone. On Roblox an
 * unmarked file is already nonstrict, so a `--!nonstrict` that annotated nothing
 * would be a setting whose entire effect was one comment.
 */
describe("type annotations", () => {
	it("are left off on Default", () => {
		expect(compile(graph("default"), registry).code).toContain("local health = 100");
	});

	it("are written under both checked modes", () => {
		for (const mode of ["nonstrict", "strict"] as const) {
			expect(compile(graph(mode), registry).code, mode).toContain("local health: number = 100");
		}
	});
});

describe("graphs written before the dropdown existed", () => {
	/** `strict: true` is what every graph made in the editor had. */
	it("reads a ticked checkbox as Strict Mode", () => {
		const raw = { ...graph("strict"), strict: true } as unknown as NodeScript;
		delete (raw as { typecheck?: unknown }).typecheck;
		expect(migrateScript(raw).script.typecheck).toBe("strict");
	});

	it("reads an unticked one as Default, not as the new-graph default", () => {
		const raw = { ...graph("strict"), strict: false } as unknown as NodeScript;
		delete (raw as { typecheck?: unknown }).typecheck;
		expect(migrateScript(raw).script.typecheck).toBe("default");
	});

	/**
	 * The rename has to be silent. Every one of these files converts, and a note
	 * on each would be a paragraph of migration output saying nothing happened.
	 */
	it("says nothing about it", () => {
		const raw = { ...graph("strict"), strict: true } as unknown as NodeScript;
		expect(migrateScript(raw).notes).toEqual([]);
	});

	/**
	 * Otherwise the old key rides along in every save, and a file converted years
	 * ago still looks like it needs converting.
	 */
	it("drops the old key rather than carrying it", () => {
		const raw = { ...graph("strict"), strict: true } as unknown as NodeScript;
		const migrated = migrateScript(raw).script;
		expect("strict" in migrated).toBe(false);
		expect(serialiseScript(migrated)).not.toContain("strict\":");
	});
});

describe("a mode this build does not recognise", () => {
	/**
	 * A graph from a later build. Falling back to `default` emits *less* than
	 * asked for; falling back to `strict` would turn on checking nobody chose,
	 * against a graph this build already only half understands.
	 */
	it("falls back to Default", () => {
		const raw = { ...graph("strict"), typecheck: "pedantic" } as unknown as NodeScript;
		expect(migrateScript(raw).script.typecheck).toBe("default");
	});

	it("takes a graph with no opinion at all as Strict Mode", () => {
		const raw = graph("strict");
		delete (raw as { typecheck?: unknown }).typecheck;
		expect(migrateScript(raw).script.typecheck).toBe("strict");
	});
});

describe("what the mode is part of", () => {
	/**
	 * The output hash is what decides whether a compile is a no-op. If the mode
	 * were left out of it, switching mode and recompiling would leave the old
	 * file on disk.
	 */
	it("changes the serialised graph, so a recompile is not skipped", () => {
		expect(serialiseScript(graph("strict"))).not.toBe(serialiseScript(graph("nonstrict")));
	});
});
