/**
 * The source of `src/core/docs/demoLayout.gen.ts`, from the demo graphs' layout.
 *
 * Apart from `fold-demo-layout.mjs`, which reads the project, so a test can
 * write a layout without one.
 */

const HEADER = `// Generated by scripts/fold-demo-layout.mjs. Do not edit by hand.
/**
 * Where the demo graphs' nodes sit, taken from the project.
 *
 * Generated by \`scripts/fold-demo-layout.mjs\` — do not edit by hand. The
 * placement in \`demos.ts\` says which column a node belongs in, which is the
 * right way to *author* a graph and a poor way to finish one; this is the
 * arrangement somebody made in the editor, which is what the page draws.
 *
 * Keyed by the demo's slug, then by node id.
 */
export const DEMO_LAYOUT: Record<string, Record<string, { x: number; y: number }>> = {`;

/**
 * The module, keyed by slug and then by node id.
 *
 * A node id is whatever the editor made it, and a UUID written bare is not a
 * property name, so an id that is not an identifier is quoted.
 *
 * @param {Record<string, Record<string, { x: number; y: number }>>} layout
 * @returns {string}
 */
export function demoLayoutSource(layout) {
	const key = (/** @type {string} */ id) =>
		/^[A-Za-z_$][\w$]*$/.test(id) ? id : JSON.stringify(id);
	const body = Object.entries(layout)
		.map(([slug, nodes]) => {
			const rows = Object.entries(nodes)
				.map(([id, at]) => `\t\t${key(id)}: { x: ${at.x}, y: ${at.y} },`)
				.join("\n");
			return `\t${JSON.stringify(slug)}: {\n${rows}\n\t},`;
		})
		.join("\n");
	return `${HEADER}\n${body}\n};\n`;
}
