/**
 * The licences Roswaal carries by hand, compiled into `src/core/licenceData.ts`.
 *
 * `notices/upstream/` holds each one as its holder published it, and
 * `notices/upstream/sources.json` says where each came from. Everything that
 * shows a licence -- Settings, the documentation in the editor and the static
 * site, the generated notices file -- reads this one module, for the reason
 * `build-themes.mjs` gives for its own: a browser bundle cannot open a folder.
 *
 * Each entry carries its text and the SHA-256 of that text, so a reader can
 * check the copy against the original rather than take it on trust.
 */

import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

export const LICENCE_MODULE_HEADER =
	"// Generated by scripts/build-licences.mjs. Do not edit by hand.";

/** Every licence in `notices/upstream/`, in the order `sources.json` lists them. */
export async function loadCarried(root) {
	const dir = join(root, "notices", "upstream");
	const sources = JSON.parse(await readFile(join(dir, "sources.json"), "utf8"));
	const files = (await readdir(dir)).filter((f) => f.endsWith(".txt")).sort();
	const problems = [];

	const listed = new Set(sources.map((s) => s.file));
	for (const file of files) {
		if (!listed.has(file)) problems.push(`${file} is in notices/upstream/ but not in sources.json`);
	}

	const carried = [];
	for (const source of sources) {
		for (const key of ["file", "name", "holder", "spdx", "covers", "source", "url", "retrieved"]) {
			if (typeof source[key] !== "string" || source[key] === "") {
				problems.push(`sources.json: ${source.file ?? "an entry"} has no ${key}`);
			}
		}
		if (!files.includes(source.file)) {
			problems.push(`sources.json names ${source.file}, which is not in notices/upstream/`);
			continue;
		}
		// LF whatever the checkout did, though `.gitattributes` keeps these
		// files as fetched: the hash is of the text as published.
		const text = lf(await readFile(join(dir, source.file), "utf8"));
		const sha256 = createHash("sha256").update(text, "utf8").digest("hex");
		carried.push({ ...source, path: `notices/upstream/${source.file}`, sha256, text });
	}

	if (problems.length > 0) throw new Error(problems.join("\n"));
	return carried;
}

/** The module's source. */
export function renderLicenceModule(carried) {
	return [
		LICENCE_MODULE_HEADER,
		"/**",
		" * The licences Roswaal carries by hand, each exactly as its holder published it.",
		" *",
		" * Source: `notices/upstream/*.txt`, and where each came from in",
		" * `notices/upstream/sources.json`. The packages a build bundles are not here:",
		" * each build lists its own in `THIRD-PARTY-NOTICES.txt` (`scripts/lib/notices.mjs`).",
		" */",
		"",
		"export interface CarriedLicence {",
		"\t/** The file's name under `notices/upstream/`. */",
		"\tfile: string;",
		"\t/** What it covers, as the attributions name it. */",
		"\tname: string;",
		"\tholder: string;",
		"\t/** Its SPDX identifier. */",
		"\tspdx: string;",
		"\t/** What in Roswaal it covers, in a sentence. */",
		"\tcovers: string;",
		"\t/** The upstream file it was copied from, and where to read the original. */",
		"\tsource: string;",
		"\turl: string;",
		"\t/** The day it was copied, as YYYY-MM-DD. */",
		"\tretrieved: string;",
		"\t/** Where it is in the repository. */",
		"\tpath: string;",
		"\t/** SHA-256 of `text`, in hex. */",
		"\tsha256: string;",
		"\ttext: string;",
		"}",
		"",
		`export const CARRIED_LICENCES: CarriedLicence[] = ${JSON.stringify(carried, null, "\t")};`,
		"",
	].join("\n");
}

/** Whether `src/core/licenceData.ts` is what `notices/upstream/` compiles to now. */
export async function licenceModuleIsCurrent(root) {
	const output = renderLicenceModule(await loadCarried(root));
	const existing = await readFile(licenceModulePath(root), "utf8").catch(() => null);
	return existing !== null && lf(existing) === lf(output);
}

/** Where the generated module goes. */
export function licenceModulePath(root) {
	return join(root, "src", "core", "licenceData.ts");
}

/** Text with LF line endings, whatever it was checked out with. */
function lf(text) {
	return text.replace(/\r\n/g, "\n");
}
