/**
 * Generated by `scripts/build-statics.mjs` from Roblox's creator-docs.
 * Do not edit by hand; run `npm run build:statics` and commit the result.
 *
 * What a datatype's own name reaches after a dot: its constructors,
 * constants and static functions, once each. See the script for why.
 */

export interface DatatypeStatic {
	name: string;
	kind: "constructor" | "constant" | "function";
	/** The signature of a constructor or function, or a constant's type. */
	detail: string;
	summary: string;
}
export const DATATYPE_STATICS: Record<string, readonly DatatypeStatic[]> = {
	"Axes": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(axes: Tuple)",
			"summary": "Creates a new Axes using list of axes and/or faces."
		}
	],
	"BrickColor": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(val: number) +3 more",
			"summary": "Constructs a BrickColor from its numerical index."
		},
		{
			"name": "palette",
			"kind": "constructor",
			"detail": "(paletteValue: number)",
			"summary": "Constructs a BrickColor from its palette index."
		},
		{
			"name": "random",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a random BrickColor."
		},
		{
			"name": "White",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"White\" BrickColor."
		},
		{
			"name": "Gray",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Medium stone grey\" BrickColor."
		},
		{
			"name": "DarkGray",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Dark stone grey\" BrickColor."
		},
		{
			"name": "Black",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Black\" BrickColor."
		},
		{
			"name": "Red",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright red\" BrickColor."
		},
		{
			"name": "Yellow",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright yellow\" BrickColor."
		},
		{
			"name": "Green",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Dark green\" BrickColor."
		},
		{
			"name": "Blue",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright blue\" BrickColor."
		}
	],
	"CFrame": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +5 more",
			"summary": "Returns a blank identity CFrame."
		},
		{
			"name": "lookAt",
			"kind": "constructor",
			"detail": "(at: Vector3, lookAt: Vector3, up: Vector3)",
			"summary": "Returns a CFrame with the position of the first Vector3 and an orientation pointed toward the second."
		},
		{
			"name": "lookAlong",
			"kind": "constructor",
			"detail": "(at: Vector3, direction: Vector3, up: Vector3)",
			"summary": "Returns a CFrame with the position of the first Vector3 and an orientation directed along the second."
		},
		{
			"name": "fromRotationBetweenVectors",
			"kind": "constructor",
			"detail": "(from: Vector3, to: Vector3)",
			"summary": "Returns a CFrame representing the orientation needed to rotate from the first Vector3 to the second, with the position set to zero."
		},
		{
			"name": "fromEulerAngles",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number, order: RotationOrder)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians."
		},
		{
			"name": "fromEulerAnglesXYZ",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians using RotationOrder.XYZ."
		},
		{
			"name": "fromEulerAnglesYXZ",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians using RotationOrder.YXZ."
		},
		{
			"name": "Angles",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Equivalent to CFrame.fromEulerAnglesXYZ()."
		},
		{
			"name": "fromOrientation",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Equivalent to CFrame.fromEulerAnglesYXZ()."
		},
		{
			"name": "fromAxisAngle",
			"kind": "constructor",
			"detail": "(v: Vector3, r: number)",
			"summary": "Returns a rotated CFrame from a unit Vector3 and a rotation in radians."
		},
		{
			"name": "fromMatrix",
			"kind": "constructor",
			"detail": "(pos: Vector3, vX: Vector3, vY: Vector3, vZ: Vector3)",
			"summary": "Returns a CFrame from a translation and the columns of a rotation matrix."
		},
		{
			"name": "identity",
			"kind": "constant",
			"detail": "CFrame",
			"summary": "An identity CFrame with no translation or rotation."
		}
	],
	"Color3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(red: number, green: number, blue: number)",
			"summary": "Returns a Color3 with the given red, green, and blue values."
		},
		{
			"name": "fromRGB",
			"kind": "constructor",
			"detail": "(red: number, green: number, blue: number)",
			"summary": "Returns a Color3 from given components within the range of 0 to 255."
		},
		{
			"name": "fromHSV",
			"kind": "constructor",
			"detail": "(hue: number, saturation: number, value: number)",
			"summary": "Returns a Color3 from the given hue, saturation, and value components."
		},
		{
			"name": "fromHex",
			"kind": "constructor",
			"detail": "(hex: string)",
			"summary": "Returns a Color3 from a given hex value."
		},
		{
			"name": "toHSV",
			"kind": "function",
			"detail": "(color: Color3)",
			"summary": "Returns the hue, saturation, and value of a Color3."
		}
	],
	"ColorSequence": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(c: Color3) +2 more",
			"summary": "Returns a new ColorSequence that is entirely the specified color."
		}
	],
	"ColorSequenceKeypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, color: Color3)",
			"summary": "Returns a ColorSequenceKeypoint from the given time and color."
		}
	],
	"Content": [
		{
			"name": "fromUri",
			"kind": "constructor",
			"detail": "(uri: string)",
			"summary": "Returns a new `Content` with an [asset URI](../../../projects/assets/index.md#asset-uris) `string` value referencing content external to the place."
		},
		{
			"name": "fromAssetId",
			"kind": "constructor",
			"detail": "(assetId: number)",
			"summary": "Returns a new `Content` from a numeric asset ID."
		},
		{
			"name": "fromObject",
			"kind": "constructor",
			"detail": "(object: Object)",
			"summary": "Returns a new `Content` with a strong reference to an Object."
		},
		{
			"name": "none",
			"kind": "constant",
			"detail": "Content",
			"summary": "An empty `Content` value with Content.SourceType of ContentSourceType."
		}
	],
	"DateTime": [
		{
			"name": "now",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a DateTime representing the current moment in time."
		},
		{
			"name": "fromUnixTimestamp",
			"kind": "constructor",
			"detail": "(unixTimestamp: number)",
			"summary": "Returns a DateTime representing the given Unix timestamp."
		},
		{
			"name": "fromUnixTimestampMillis",
			"kind": "constructor",
			"detail": "(unixTimestampMillis: number)",
			"summary": "Returns a DateTime representing the given Unix timestamp in milliseconds."
		},
		{
			"name": "fromUniversalTime",
			"kind": "constructor",
			"detail": "(year: number, month: number, day: number, hour: number, minute: number, second: number, millisecond: number)",
			"summary": "Returns a new DateTime using the given units from a UTC time."
		},
		{
			"name": "fromLocalTime",
			"kind": "constructor",
			"detail": "(year: number, month: number, day: number, hour: number, minute: number, second: number, millisecond: number)",
			"summary": "Returns a new DateTime using the given units from a local time."
		},
		{
			"name": "fromIsoDate",
			"kind": "constructor",
			"detail": "(isoDate: string)",
			"summary": "Returns a DateTime from an ISO 8601 date-time string (in UTC)."
		}
	],
	"DockWidgetPluginGuiInfo": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(InitialDockState: InitialDockState, InitialEnabled: bool, InitialEnabledShouldOverrideRestore: bool, FloatingXSize: number, FloatingYSize: number, MinWidth: number, MinHeight: number)",
			"summary": "Returns a new DockWidgetPluginGuiInfo object."
		}
	],
	"Faces": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(normalIds...: Tuple)",
			"summary": "Returns a `Faces` with the corresponding face of each passed NormalId as `true`."
		}
	],
	"FloatCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: number, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new FloatCurveKey from the given time and value."
		}
	],
	"Font": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(family: Content, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a new Font."
		},
		{
			"name": "fromEnum",
			"kind": "constructor",
			"detail": "(font: Font)",
			"summary": "Creates a Font from an Font value."
		},
		{
			"name": "fromName",
			"kind": "constructor",
			"detail": "(name: string, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a Font from a name like `FredokaOne`."
		},
		{
			"name": "fromId",
			"kind": "constructor",
			"detail": "(id: number, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a Font from a numerical asset ID."
		}
	],
	"Instance": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(className: string, parent: Instance?)",
			"summary": "Returns an Instance of the specified class."
		},
		{
			"name": "fromExisting",
			"kind": "constructor",
			"detail": "(existingInstance: Instance)",
			"summary": "Returns an Instance which is a copy of an existing Instance."
		}
	],
	"NumberRange": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(value: number) +1 more",
			"summary": "Returns a new NumberRange with the minimum and maximum set to the `value`."
		}
	],
	"NumberSequence": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(n: number) +2 more",
			"summary": "Returns a NumberSequence with the start and end values set to the provided `n`."
		}
	],
	"NumberSequenceKeypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: number) +1 more",
			"summary": "Returns a keypoint with the specified time and value."
		}
	],
	"OverlapParams": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a blank OverlapParams object."
		}
	],
	"Path2DControlPoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns an empty Path2DControlPoint."
		}
	],
	"PathWaypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(position: Vector3, action: PathWaypointAction, label: string)",
			"summary": "Returns a PathWaypoint object from the given Vector3 position, PathWaypointAction action, and optional string label."
		}
	],
	"PhysicalProperties": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(material: Material) +3 more",
			"summary": "Returns a PhysicalProperties with the default properties for the given material."
		}
	],
	"Random": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(seed: number)",
			"summary": "Returns a new pseudorandom generator using an optional seed."
		}
	],
	"Ray": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(Origin: Vector3, Direction: Vector3)",
			"summary": "Returns a Ray with the given `Origin` and `Direction`."
		}
	],
	"RaycastParams": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a blank RaycastParams."
		}
	],
	"Rect": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns a new **Rect** with zero Vector2 positions."
		}
	],
	"Region3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(min: Vector3, max: Vector3)",
			"summary": "Returns a new Region3 using the provided vectors as boundaries."
		}
	],
	"Region3int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(min: Vector3int16, max: Vector3int16)",
			"summary": "Returns a new Region3int16 from the provided boundaries."
		}
	],
	"RotationCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, cframe: CFrame, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new RotationCurveKey at a given time with a given CFrame."
		}
	],
	"SecurityCapabilities": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(...: SecurityCapability)",
			"summary": "Returns a new set of capabilities from zero or more SecurityCapability items."
		},
		{
			"name": "fromCurrent",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a new set of capabilities from the capabilities of the calling function."
		}
	],
	"SharedTable": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +1 more",
			"summary": "Returns a new, empty SharedTable."
		},
		{
			"name": "clear",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Removes all of the elements from the SharedTable."
		},
		{
			"name": "clone",
			"kind": "function",
			"detail": "(st: SharedTable, deep: boolean?)",
			"summary": "Creates and returns a clone of the provided SharedTable."
		},
		{
			"name": "cloneAndFreeze",
			"kind": "function",
			"detail": "(st: SharedTable, deep: boolean?)",
			"summary": "Creates and returns a frozen (read-only) clone of the provided SharedTable."
		},
		{
			"name": "increment",
			"kind": "function",
			"detail": "(st: SharedTable, key: string | number, delta: number)",
			"summary": "Adds `delta` to the value with the provided key and returns the original value."
		},
		{
			"name": "isFrozen",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Returns `true` if the SharedTable is frozen (read-only)."
		},
		{
			"name": "size",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Returns the number of elements stored in the SharedTable."
		},
		{
			"name": "update",
			"kind": "function",
			"detail": "(st: SharedTable, key: string | number, f: function)",
			"summary": "Updates the value with the provided key via the provided update function."
		}
	],
	"TweenInfo": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, easingStyle: EasingStyle, easingDirection: EasingDirection, repeatCount: number, reverses: bool, delayTime: number)",
			"summary": "Creates a new TweenInfo from the provided parameters."
		}
	],
	"UDim": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(Scale: number, Offset: number)",
			"summary": "Returns a UDim from the given components."
		}
	],
	"UDim2": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns a new UDim2 with the coordinates of two zero UDim components representing each axis."
		},
		{
			"name": "fromScale",
			"kind": "constructor",
			"detail": "(xScale: number, yScale: number)",
			"summary": "Returns a new UDim2 with the given scale components and no offsets."
		},
		{
			"name": "fromOffset",
			"kind": "constructor",
			"detail": "(xOffset: number, yOffset: number)",
			"summary": "Returns a new UDim2 with the given offset components and no scaling."
		}
	],
	"User": [
		{
			"name": "fromId",
			"kind": "constructor",
			"detail": "(domainUserId: int64)",
			"summary": "Creates a User from a domain user ID within the current experience."
		},
		{
			"name": "fromString",
			"kind": "constructor",
			"detail": "(userString: string)",
			"summary": "Creates a User from its serialized string form."
		}
	],
	"ValueCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: any, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new ValueCurveKey from the given time and value."
		}
	],
	"Vector2": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number)",
			"summary": "Returns a Vector2 from the given x and y components."
		},
		{
			"name": "zero",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a magnitude of zero."
		},
		{
			"name": "one",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on every axis."
		},
		{
			"name": "xAxis",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on the X axis."
		},
		{
			"name": "yAxis",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on the Y axis."
		}
	],
	"Vector2int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number)",
			"summary": "Returns a Vector2int16 from the given x and y components."
		}
	],
	"Vector3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number, z: number)",
			"summary": "Returns a new Vector3 from the given `x`, `y`, and `z` components."
		},
		{
			"name": "FromNormalId",
			"kind": "constructor",
			"detail": "(normal: NormalId)",
			"summary": "Returns a new Vector3 in the given direction."
		},
		{
			"name": "FromAxis",
			"kind": "constructor",
			"detail": "(axis: Axis)",
			"summary": "Returns a new Vector3 for the given axis."
		},
		{
			"name": "zero",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a magnitude of `0`."
		},
		{
			"name": "one",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on every axis."
		},
		{
			"name": "xAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **X** axis."
		},
		{
			"name": "yAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **Y** axis."
		},
		{
			"name": "zAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **Z** axis."
		}
	],
	"Vector3int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number, z: number)",
			"summary": "Returns a new Vector3int16 from the given x, y, and z components."
		}
	]
};
