/**
 * Generated by `scripts/build-statics.mjs` from Roblox's creator-docs.
 * Do not edit by hand; run `npm run build:statics` and commit the result.
 *
 * What a datatype's own name reaches after a dot — its constructors,
 * constants and static functions, once each — and one sentence on what
 * each class and datatype is. See the script for why.
 */

export interface DatatypeStatic {
	name: string;
	kind: "constructor" | "constant" | "function";
	/** The signature of a constructor or function, or a constant's type. */
	detail: string;
	summary: string;
}
export const DATATYPE_STATICS: Record<string, readonly DatatypeStatic[]> = {
	"Axes": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(axes: Tuple)",
			"summary": "Creates a new Axes using list of axes and/or faces."
		}
	],
	"BrickColor": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(val: number) +3 more",
			"summary": "Constructs a BrickColor from its numerical index."
		},
		{
			"name": "palette",
			"kind": "constructor",
			"detail": "(paletteValue: number)",
			"summary": "Constructs a BrickColor from its palette index."
		},
		{
			"name": "random",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a random BrickColor."
		},
		{
			"name": "White",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"White\" BrickColor."
		},
		{
			"name": "Gray",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Medium stone grey\" BrickColor."
		},
		{
			"name": "DarkGray",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Dark stone grey\" BrickColor."
		},
		{
			"name": "Black",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Black\" BrickColor."
		},
		{
			"name": "Red",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright red\" BrickColor."
		},
		{
			"name": "Yellow",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright yellow\" BrickColor."
		},
		{
			"name": "Green",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Dark green\" BrickColor."
		},
		{
			"name": "Blue",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns the \"Bright blue\" BrickColor."
		}
	],
	"CFrame": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +5 more",
			"summary": "Returns a blank identity CFrame."
		},
		{
			"name": "lookAt",
			"kind": "constructor",
			"detail": "(at: Vector3, lookAt: Vector3, up: Vector3)",
			"summary": "Returns a CFrame with the position of the first Vector3 and an orientation pointed toward the second."
		},
		{
			"name": "lookAlong",
			"kind": "constructor",
			"detail": "(at: Vector3, direction: Vector3, up: Vector3)",
			"summary": "Returns a CFrame with the position of the first Vector3 and an orientation directed along the second."
		},
		{
			"name": "fromRotationBetweenVectors",
			"kind": "constructor",
			"detail": "(from: Vector3, to: Vector3)",
			"summary": "Returns a CFrame representing the orientation needed to rotate from the first Vector3 to the second, with the position set to zero."
		},
		{
			"name": "fromEulerAngles",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number, order: RotationOrder)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians."
		},
		{
			"name": "fromEulerAnglesXYZ",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians using RotationOrder.XYZ."
		},
		{
			"name": "fromEulerAnglesYXZ",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Returns a rotated CFrame from angles `rx`, `ry`, and `rz` in radians using RotationOrder.YXZ."
		},
		{
			"name": "Angles",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Equivalent to CFrame.fromEulerAnglesXYZ()."
		},
		{
			"name": "fromOrientation",
			"kind": "constructor",
			"detail": "(rx: number, ry: number, rz: number)",
			"summary": "Equivalent to CFrame.fromEulerAnglesYXZ()."
		},
		{
			"name": "fromAxisAngle",
			"kind": "constructor",
			"detail": "(v: Vector3, r: number)",
			"summary": "Returns a rotated CFrame from a unit Vector3 and a rotation in radians."
		},
		{
			"name": "fromMatrix",
			"kind": "constructor",
			"detail": "(pos: Vector3, vX: Vector3, vY: Vector3, vZ: Vector3)",
			"summary": "Returns a CFrame from a translation and the columns of a rotation matrix."
		},
		{
			"name": "identity",
			"kind": "constant",
			"detail": "CFrame",
			"summary": "An identity CFrame with no translation or rotation."
		}
	],
	"Color3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(red: number, green: number, blue: number)",
			"summary": "Returns a Color3 with the given red, green, and blue values."
		},
		{
			"name": "fromRGB",
			"kind": "constructor",
			"detail": "(red: number, green: number, blue: number)",
			"summary": "Returns a Color3 from given components within the range of 0 to 255."
		},
		{
			"name": "fromHSV",
			"kind": "constructor",
			"detail": "(hue: number, saturation: number, value: number)",
			"summary": "Returns a Color3 from the given hue, saturation, and value components."
		},
		{
			"name": "fromHex",
			"kind": "constructor",
			"detail": "(hex: string)",
			"summary": "Returns a Color3 from a given hex value."
		},
		{
			"name": "toHSV",
			"kind": "function",
			"detail": "(color: Color3)",
			"summary": "Returns the hue, saturation, and value of a Color3."
		}
	],
	"ColorSequence": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(c: Color3) +2 more",
			"summary": "Returns a new ColorSequence that is entirely the specified color."
		}
	],
	"ColorSequenceKeypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, color: Color3)",
			"summary": "Returns a ColorSequenceKeypoint from the given time and color."
		}
	],
	"Content": [
		{
			"name": "fromUri",
			"kind": "constructor",
			"detail": "(uri: string)",
			"summary": "Returns a new `Content` with an [asset URI](../../../projects/assets/index.md#asset-uris) `string` value referencing content external to the place."
		},
		{
			"name": "fromAssetId",
			"kind": "constructor",
			"detail": "(assetId: number)",
			"summary": "Returns a new `Content` from a numeric asset ID."
		},
		{
			"name": "fromObject",
			"kind": "constructor",
			"detail": "(object: Object)",
			"summary": "Returns a new `Content` with a strong reference to an Object."
		},
		{
			"name": "none",
			"kind": "constant",
			"detail": "Content",
			"summary": "An empty `Content` value with Content.SourceType of ContentSourceType."
		}
	],
	"DateTime": [
		{
			"name": "now",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a DateTime representing the current moment in time."
		},
		{
			"name": "fromUnixTimestamp",
			"kind": "constructor",
			"detail": "(unixTimestamp: number)",
			"summary": "Returns a DateTime representing the given Unix timestamp."
		},
		{
			"name": "fromUnixTimestampMillis",
			"kind": "constructor",
			"detail": "(unixTimestampMillis: number)",
			"summary": "Returns a DateTime representing the given Unix timestamp in milliseconds."
		},
		{
			"name": "fromUniversalTime",
			"kind": "constructor",
			"detail": "(year: number, month: number, day: number, hour: number, minute: number, second: number, millisecond: number)",
			"summary": "Returns a new DateTime using the given units from a UTC time."
		},
		{
			"name": "fromLocalTime",
			"kind": "constructor",
			"detail": "(year: number, month: number, day: number, hour: number, minute: number, second: number, millisecond: number)",
			"summary": "Returns a new DateTime using the given units from a local time."
		},
		{
			"name": "fromIsoDate",
			"kind": "constructor",
			"detail": "(isoDate: string)",
			"summary": "Returns a DateTime from an ISO 8601 date-time string (in UTC)."
		}
	],
	"DockWidgetPluginGuiInfo": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(InitialDockState: InitialDockState, InitialEnabled: bool, InitialEnabledShouldOverrideRestore: bool, FloatingXSize: number, FloatingYSize: number, MinWidth: number, MinHeight: number)",
			"summary": "Returns a new DockWidgetPluginGuiInfo object."
		}
	],
	"Faces": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(normalIds...: Tuple)",
			"summary": "Returns a `Faces` with the corresponding face of each passed NormalId as `true`."
		}
	],
	"FloatCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: number, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new FloatCurveKey from the given time and value."
		}
	],
	"Font": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(family: Content, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a new Font."
		},
		{
			"name": "fromEnum",
			"kind": "constructor",
			"detail": "(font: Font)",
			"summary": "Creates a Font from an Font value."
		},
		{
			"name": "fromName",
			"kind": "constructor",
			"detail": "(name: string, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a Font from a name like `FredokaOne`."
		},
		{
			"name": "fromId",
			"kind": "constructor",
			"detail": "(id: number, weight: FontWeight, style: FontStyle)",
			"summary": "Creates a Font from a numerical asset ID."
		}
	],
	"Instance": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(className: string, parent: Instance?)",
			"summary": "Returns an Instance of the specified class."
		},
		{
			"name": "fromExisting",
			"kind": "constructor",
			"detail": "(existingInstance: Instance)",
			"summary": "Returns an Instance which is a copy of an existing Instance."
		}
	],
	"NumberRange": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(value: number) +1 more",
			"summary": "Returns a new NumberRange with the minimum and maximum set to the `value`."
		}
	],
	"NumberSequence": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(n: number) +2 more",
			"summary": "Returns a NumberSequence with the start and end values set to the provided `n`."
		}
	],
	"NumberSequenceKeypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: number) +1 more",
			"summary": "Returns a keypoint with the specified time and value."
		}
	],
	"OverlapParams": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a blank OverlapParams object."
		}
	],
	"Path2DControlPoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns an empty Path2DControlPoint."
		}
	],
	"PathWaypoint": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(position: Vector3, action: PathWaypointAction, label: string)",
			"summary": "Returns a PathWaypoint object from the given Vector3 position, PathWaypointAction action, and optional string label."
		}
	],
	"PhysicalProperties": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(material: Material) +3 more",
			"summary": "Returns a PhysicalProperties with the default properties for the given material."
		}
	],
	"Random": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(seed: number)",
			"summary": "Returns a new pseudorandom generator using an optional seed."
		}
	],
	"Ray": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(Origin: Vector3, Direction: Vector3)",
			"summary": "Returns a Ray with the given `Origin` and `Direction`."
		}
	],
	"RaycastParams": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a blank RaycastParams."
		}
	],
	"Rect": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns a new **Rect** with zero Vector2 positions."
		}
	],
	"Region3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(min: Vector3, max: Vector3)",
			"summary": "Returns a new Region3 using the provided vectors as boundaries."
		}
	],
	"Region3int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(min: Vector3int16, max: Vector3int16)",
			"summary": "Returns a new Region3int16 from the provided boundaries."
		}
	],
	"RotationCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, cframe: CFrame, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new RotationCurveKey at a given time with a given CFrame."
		}
	],
	"SecurityCapabilities": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(...: SecurityCapability)",
			"summary": "Returns a new set of capabilities from zero or more SecurityCapability items."
		},
		{
			"name": "fromCurrent",
			"kind": "constructor",
			"detail": "()",
			"summary": "Returns a new set of capabilities from the capabilities of the calling function."
		}
	],
	"SharedTable": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +1 more",
			"summary": "Returns a new, empty SharedTable."
		},
		{
			"name": "clear",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Removes all of the elements from the SharedTable."
		},
		{
			"name": "clone",
			"kind": "function",
			"detail": "(st: SharedTable, deep: boolean?)",
			"summary": "Creates and returns a clone of the provided SharedTable."
		},
		{
			"name": "cloneAndFreeze",
			"kind": "function",
			"detail": "(st: SharedTable, deep: boolean?)",
			"summary": "Creates and returns a frozen (read-only) clone of the provided SharedTable."
		},
		{
			"name": "increment",
			"kind": "function",
			"detail": "(st: SharedTable, key: string | number, delta: number)",
			"summary": "Adds `delta` to the value with the provided key and returns the original value."
		},
		{
			"name": "isFrozen",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Returns `true` if the SharedTable is frozen (read-only)."
		},
		{
			"name": "size",
			"kind": "function",
			"detail": "(st: SharedTable)",
			"summary": "Returns the number of elements stored in the SharedTable."
		},
		{
			"name": "update",
			"kind": "function",
			"detail": "(st: SharedTable, key: string | number, f: function)",
			"summary": "Updates the value with the provided key via the provided update function."
		}
	],
	"TweenInfo": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, easingStyle: EasingStyle, easingDirection: EasingDirection, repeatCount: number, reverses: bool, delayTime: number)",
			"summary": "Creates a new TweenInfo from the provided parameters."
		}
	],
	"UDim": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(Scale: number, Offset: number)",
			"summary": "Returns a UDim from the given components."
		}
	],
	"UDim2": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "() +2 more",
			"summary": "Returns a new UDim2 with the coordinates of two zero UDim components representing each axis."
		},
		{
			"name": "fromScale",
			"kind": "constructor",
			"detail": "(xScale: number, yScale: number)",
			"summary": "Returns a new UDim2 with the given scale components and no offsets."
		},
		{
			"name": "fromOffset",
			"kind": "constructor",
			"detail": "(xOffset: number, yOffset: number)",
			"summary": "Returns a new UDim2 with the given offset components and no scaling."
		}
	],
	"User": [
		{
			"name": "fromId",
			"kind": "constructor",
			"detail": "(domainUserId: int64)",
			"summary": "Creates a User from a domain user ID within the current experience."
		},
		{
			"name": "fromString",
			"kind": "constructor",
			"detail": "(userString: string)",
			"summary": "Creates a User from its serialized string form."
		}
	],
	"ValueCurveKey": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(time: number, value: any, Interpolation: KeyInterpolationMode)",
			"summary": "Returns a new ValueCurveKey from the given time and value."
		}
	],
	"Vector2": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number)",
			"summary": "Returns a Vector2 from the given x and y components."
		},
		{
			"name": "zero",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a magnitude of zero."
		},
		{
			"name": "one",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on every axis."
		},
		{
			"name": "xAxis",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on the X axis."
		},
		{
			"name": "yAxis",
			"kind": "constant",
			"detail": "Vector2",
			"summary": "A Vector2 with a value of 1 on the Y axis."
		}
	],
	"Vector2int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number)",
			"summary": "Returns a Vector2int16 from the given x and y components."
		}
	],
	"Vector3": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number, z: number)",
			"summary": "Returns a new Vector3 from the given `x`, `y`, and `z` components."
		},
		{
			"name": "FromNormalId",
			"kind": "constructor",
			"detail": "(normal: NormalId)",
			"summary": "Returns a new Vector3 in the given direction."
		},
		{
			"name": "FromAxis",
			"kind": "constructor",
			"detail": "(axis: Axis)",
			"summary": "Returns a new Vector3 for the given axis."
		},
		{
			"name": "zero",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a magnitude of `0`."
		},
		{
			"name": "one",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on every axis."
		},
		{
			"name": "xAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **X** axis."
		},
		{
			"name": "yAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **Y** axis."
		},
		{
			"name": "zAxis",
			"kind": "constant",
			"detail": "Vector3",
			"summary": "A Vector3 with a value of `1` on the **Z** axis."
		}
	],
	"Vector3int16": [
		{
			"name": "new",
			"kind": "constructor",
			"detail": "(x: number, y: number, z: number)",
			"summary": "Returns a new Vector3int16 from the given x, y, and z components."
		}
	]
};

/** One sentence per class, by class name. */
export const CLASS_SUMMARIES: Record<string, string> = {
	"Accessory": "An item that a Character can wear.",
	"Animation": "References an animation asset which can be loaded by an AnimationController.",
	"AngularVelocity": "Applies torque on an assembly to maintain a constant angular velocity.",
	"Accoutrement": "An object that can attach to a player's character.",
	"AdService": "The service responsible for in-experience advertising.",
	"AnalyticsService": "Collection of methods that allows you to track how users interact with your experiences.",
	"AccessoryDescription": "Describes the appearance of an Accessory for the HumanoidDescription.",
	"AdvancedDragger": "An unfinished advanced variant of the Dragger class.",
	"AdPortal": "A portal that teleports players to a sponsored experience as part of immersive ads.",
	"AlignOrientation": "Constraint which applies torque to align two attachments, or to align one attachment with a goal orientation.",
	"AirController": "A physics character controller that governs movement while a character is airborne.",
	"AlignPosition": "Constraint which applies force to move two attachments together, or to move one attachment to a goal position.",
	"AnimationClip": "Represents all types of animation data that the Roblox animation system can consume.",
	"AdGui": "A surface-based GUI that displays immersive ads on a face of a Part in the 3D world.",
	"AnimationClipProvider": "Provides functions to load and preview AnimationClip.",
	"Actor": "An Actor is a container for code that can be safely split into its own thread.",
	"ArcHandles": "The ArcHandles object places 3D arc handles around any 3D object that its PartAdornment.Adornee is set to.",
	"AssetService": "A non-replicated service that handles asset-related queries to the Roblox web API.",
	"Animator": "Responsible for the playback and replication of Animation.",
	"Atmosphere": "The Atmosphere object pushes Roblox closer toward realistic environments where sunlight scatters in different ways depending on density and other air particle properties.",
	"AnimationConstraint": "Aligns two BasePart with an animate-able kinematic or force-based joint that supports physical simulation (ragdoll, arm strength).",
	"Attachment": "Defines a point and orientation relative to an ancestor PVInstance, Bone, or another Attachment.",
	"AnimationRigData": "Used to store information regarding the model an animation was authored for.",
	"AtmosphereSensor": "A SensorBase that outputs data about the AtmosphereSensor.AirDensity and AtmosphereSensor.RelativeWindVelocity at the sensor's position.",
	"AudioAnalyzer": "Takes measurements from audio streams that are connected to it via one or more Wire.",
	"AudioChannelMixer": "Combines multiple audio streams into a single, multichannel audio stream.",
	"AnimationTrack": "Controls the playback of an animation on an Animator.",
	"AssetPatchSettings": "Configures a single patch asset built by IncrementalPatchBuilder and served through AssetDeliveryProxy.",
	"AnimationNodeDefinition": "A single node within an animation graph, connected to other nodes through named input pins.",
	"AudioChannelSplitter": "Splits an audio stream into component channels so that each can be processed independently.",
	"AnimationController": "Allows animations to be loaded and applied to a character or model in place of a Humanoid.",
	"AssetDeliveryProxy": "Runs a local HTTP server that serves assets to real devices.",
	"AudioDeviceOutput": "Accepts audio streams to be rendered out to physical hardware devices such as speakers or headphones.",
	"AudioListener": "Records an audio stream from its surrounding AudioEmitter in the 3D world.",
	"AudioEmitter": "Emits audio streams into the world.",
	"AudioDeviceInput": "Produces audio streams from physical devices, such as microphones.",
	"AudioEqualizer": "Adjusts the frequency content of audio streams.",
	"AudioLimiter": "Limits how loud audio streams are allowed to be.",
	"AudioGate": "Mutes audio streams that fall below a certain volume threshold.",
	"AudioDistortion": "Distorts audio streams, making them sound fuzzier, grittier, and louder.",
	"AudioFlanger": "Imparts a whooshing or sweeping sound on audio streams.",
	"AudioEcho": "Overlays delayed copies of audio streams.",
	"AudioCompressor": "Adjusts the dynamic range of input streams.",
	"AudioFilter": "Adjusts the frequency content of audio streams.",
	"AudioFader": "Adjusts the volume of audio streams.",
	"AudioPages": "A special version of the Pages class returned by AssetService:SearchAudioAsync().",
	"AudioChorus": "Makes an audio stream sound more voluminous.",
	"AudioPitchShifter": "Adjusts the perceived pitch of audio streams.",
	"BadgeService": "Provides information on badges and awards them.",
	"AudioPlayer": "Used to play audio assets.",
	"AudioRecorder": "Records audio streams in-experience.",
	"BallSocketConstraint": "Forces its two attachments into the same position and allows them to freely rotate about all three axes, with optional limits to restrict both tilt and twist.",
	"BasePart": "The abstract base class for in-world objects that physically interact.",
	"AudioTextToSpeech": "Plays text as speech audio.",
	"AudioSearchParams": "Instance to be passed to AssetService:SearchAudioAsync() to search for audio assets.",
	"BanHistoryPages": "Returned by Players:GetBanHistoryAsync to view the entire ban and unban history of any UserId.",
	"AudioSpeechToText": "Converts spoken audio into text.",
	"AvatarCreationService": "A service to support developer avatar creators.",
	"AvatarEditorService": "A service to support developer Avatar Editors.",
	"BackpackItem": "BackpackItem is an abstract class for backpack items such as HopperBins and Tools.",
	"AudioReverb": "Reverberates audio streams.",
	"AudioTremolo": "Creates a trembling effect on a sound by varying the volume of the sound up and down.",
	"Backpack": "A container object that holds a player's inventory.",
	"BaseCoreGuiConfiguration": "Base class for the configuration objects that control individual built-in CoreGui elements.",
	"BasePlayerGui": "`BasePlayerGui` is an abstract class which the GUI drawing storage classes inherit from.",
	"BillboardGui": "A container for GuiObject that renders in 3D space facing the camera.",
	"BlurEffect": "Applies a blur to the entire game world.",
	"BloomEffect": "Simulates the camera viewing a very bright light.",
	"BodyForce": "Applies a constant force to an object.",
	"BindableFunction": "An object which allows for synchronous two-way communication between scripts on the same side of the client-server boundary.",
	"BlockMesh": "The BlockMesh object applies a 'brick' mesh to the BasePart it is parented to.",
	"BodyAngularVelocity": "Applies a torque to maintain a constant angular velocity.",
	"BaseWrap": "Abstract base class for WrapTarget and WrapLayer that stores cage mesh data for layered clothing deformation.",
	"BaseRemoteEvent": "Abstract base class inherited by RemoteEvent and UnreliableRemoteEvent for asynchronous, one-way communication across the client-server boundary.",
	"BaseScript": "The base class for all script objects which run automatically.",
	"BevelMesh": "An abstract class that BlockMesh and CylinderMesh inherit from.",
	"BinaryStringValue": "An internal type of StringValue object, that stores a `BinaryString` value.",
	"BindableEvent": "An object which enables custom events through asynchronous one-way communication between scripts on the same side of the client-server boundary.",
	"BodyColors": "For a Humanoid character, the BodyColors will specify the colors for the different body parts.",
	"Beam": "Connects two Attachment by drawing a texture between them.",
	"BodyVelocity": "Applies a force to maintain a constant velocity.",
	"BubbleChatConfiguration": "Allows for customization of text chat bubbles through TextChatService.",
	"Bone": "Bones are non-rendered objects that drive the movement of one or more parts for the purposes of animation, or creating clothing and characters.",
	"Camera": "A class which defines a view of the 3D world.",
	"CacheableContentProvider": "A variant of the ContentProvider that caches assets that have already been received.",
	"BodyGyro": "Applies a torque to maintain a constant orientation.",
	"BodyMover": "Base class for objects that continually exert forces to assemblies.",
	"BodyThrust": "Applies a constant force to an object at a specific point.",
	"BodyPosition": "Applies a force to maintain a constant position.",
	"BrowserService": "Bridges the Roblox client to its native web browser or WebView.",
	"BoolValue": "A container object for a single boolean value.",
	"BoxHandleAdornment": "A box-shaped handle that can be adorned to a BasePart.",
	"BubbleChatMessageProperties": "Overrides BubbleChatConfiguration properties for an individual bubble chat message.",
	"BrickColorValue": "A container object for a single BrickColor value.",
	"BodyPartDescription": "Describes the appearance of an avatar body part for the HumanoidDescription.",
	"BuoyancySensor": "A SensorBase that outputs data about how its BasePart is interacting with Terrain water.",
	"ChatWindowConfiguration": "Configures properties of the default chat window.",
	"CaptureService": "A service which provides control over screenshot and video capture features.",
	"ChangeHistoryService": "**Must** be used by plugins to communicate to Studio how to undo and redo the changes which they make to the experience.",
	"CFrameValue": "A container object for a single CFrame value.",
	"Capture": "A class which defines a piece of content, such as a screenshot or video, taken in-experience.",
	"CapturesPages": "A special version of the Pages class returned by CaptureService.ReadCapturesFromGalleryAsync.",
	"CanvasGroup": "Blends descendants as a flattened group with an optional color/transparency modification.",
	"ChannelTabsConfiguration": "Configures properties of the optional channel tabs in the default chat window.",
	"ChatInputBarConfiguration": "Configures properties of the default chat input bar.",
	"CatalogPages": "A special version of Pages that stores the results of an Avatar Editor catalog search.",
	"CharacterMesh": "Modifies the appearance of an R6 body part.",
	"CharacterAppearance": "The base class for objects that change the character's appearance, such as the BodyColors, CharacterMesh, ShirtGraphic, Pants and Shirt objects.",
	"Chat": "Houses the Luau code responsible for running the legacy chat system.",
	"ChorusSoundEffect": "Makes audio more voluminous by simulating multiple voices playing the same part.",
	"ChatWindowMessageProperties": "Customizes the appearance of an individual text chat message displayed in the chat window.",
	"CapturesViewConfiguration": "Controls the built-in captures view, the CoreGui element that lets players browse and manage screenshots and video captures they take within an experience.",
	"ColorGradingEffect": "Modifies how color values calculated by the renderer should be converted to the screen's color range.",
	"ConfigService": "A game service that gives access to in-experience configuration with updates in real time.",
	"CollectionService": "A service which manages instance collections using assigned tags.",
	"Clouds": "Renders realistic clouds that drift slowly across the sky.",
	"ConeHandleAdornment": "A cone-shaped handle that can be adorned to a BasePart.",
	"ClimbController": "A physics character controller that moves its ControllerManager.RootPart along a climbable surface, such as a ladder.",
	"CompressorSoundEffect": "Adjusts the dynamic range of audio.",
	"ClientReplicator": "The client-side NetworkReplicator that manages replication of data model changes between the server and itself.",
	"ClusterPacketCache": "An internal service meant to cache cluster packets.",
	"ClickDetector": "An object that provides user input on in-experience BasePart and Model.",
	"ConfigSnapshot": "A snapshot of configuration values at a given version.",
	"CommerceService": "Supports real-world purchases that you can bundle with digital benefits.",
	"ColorCorrectionEffect": "Adjusts color-related properties of the rendered world like saturation, tint, brightness, and contrast.",
	"CompositeValueCurve": "An animation curve that groups child FloatCurve which each animate a different component of a non-unary value.",
	"Color3Value": "A container object for a single Color3 value.",
	"Clothing": "Clothing is the base class for the Shirt and Pants clothing objects.",
	"CornerWedgePart": "A type of BasePart that has a corner wedge shape.",
	"ContentProvider": "Service that is used to load content, or assets, into a game.",
	"CreatorStoreService": "Provides methods for querying Creator Store product information and purchasing assets.",
	"Configuration": "A container object designed to hold value objects.",
	"ControllerService": "Container class for the HumanoidController among other classes.",
	"ControllerPartSensor": "A SensorBase that outputs data about another BasePart based on Humanoid floor and ladder detection logic.",
	"ControllerManager": "Manages simulated motion control for its assigned ControllerManager.RootPart .",
	"ConfigureServerService": "Configures a server's DataModel for a place session during game-server startup.",
	"Controller": "The base class for controller objects, such as the HumanoidController object.",
	"CoreGuiConfiguration": "Service that groups the configuration objects controlling Roblox's built-in CoreGui elements.",
	"Constraint": "The base class for constraint-based objects.",
	"CoreGui": "The CoreGui is a service used to store Guis created in-game by Roblox for the core user interface found in every game (such as the game menu, the playerlist, the backpack, etc.).",
	"ControllerSensor": "An abstract base class for SensorBase types that supply sensory data to a character controller.",
	"CookiesService": "A backend service used by Roblox to control HTTP cookies.",
	"ContextActionService": "A service used to bind user input to contextual actions.",
	"ControllerBase": "Abstract base class for the controllers that a ControllerManager uses to move its character.",
	"DataModel": "The root of Roblox's parent-child hierarchy.",
	"DataStoreKeyInfo": "An object specifying information about a particular version of the key.",
	"CylindricalConstraint": "Constrains two attachments on two parts to have a relative linear and rotational motion.",
	"CylinderHandleAdornment": "A cylinder-shaped handle that can be adorned to a BasePart.",
	"DataStore": "A GlobalDataStore that also supports versioning, key metadata, and enumerating keys.",
	"DataStoreKeyPages": "A special type of Pages object whose pages contain DataStoreKey instances.",
	"CurveAnimation": "Stores animation data in the form of curves for each individual channel to animate.",
	"CustomLog": "Internal-only instance that writes text to a file in the engine's logs directory.",
	"DataStoreInfo": "Object describing data store information.",
	"CylinderMesh": "The CylinderMesh object applies a 'cylinder' mesh to the BasePart it is parented to.",
	"DataStoreKey": "Object representing a key on a DataStoreKeyPages object.",
	"DataStoreIncrementOptions": "Specifies additional parameters for a GlobalDataStore:IncrementAsync() call.",
	"DataStoreGetOptions": "Specifies additional parameters for a GlobalDataStore:GetAsync() call.",
	"DataModelMesh": "The DataModelMesh is an abstract class from which mesh classes descend.",
	"DepthOfFieldEffect": "Simulates a camera lens by blurring parts of a scene not in focus.",
	"Dialog": "Creates NPC billboard-style dialog bubbles.",
	"DataStoreVersionPages": "A special type of Pages object whose pages contain DataStoreObjectVersionInfo instances.",
	"DockWidgetPluginGui": "A PluginGui that displays its contents in a dockable, resizable Roblox Studio window.",
	"DataStoreOptions": "Object used to provide additional parameters to DataStoreService:GetDataStore().",
	"DataStoreSetOptions": "Specifies additional parameters for a GlobalDataStore:SetAsync() call.",
	"Debris": "Allows scheduling the guaranteed destruction of an object without yielding.",
	"DebugSettings": "Collection of various developer-facing diagnostics information.",
	"DataStorePages": "A Pages object that allows iteration through OrderedDataStore key/value pairs.",
	"DialogChoice": "Used to craft the further choices available to players who have started a dialog conversation with an NPC.",
	"DataStoreObjectVersionInfo": "An instance describing version information for a key.",
	"DataStoreService": "A game service that gives access to persistent data storage across places in a game.",
	"DistortionSoundEffect": "Distorts audio, making it sound fuzzier and overdriven.",
	"DigitsRigDescription": "Maps the 15 phalanx joints of one hand (5 fingers, 3 joints each) and exposes forward- and inverse-kinematics helpers for controlling finger poses at runtime.",
	"Decal": "Applies an image texture to a face of a parent BasePart.",
	"DataStoreListingPages": "A special type of Pages object whose pages contain DataStoreInfo instances.",
	"ExperienceInviteOptions": "Used to customize a player invite prompt.",
	"EditableImage": "Object which allows for the runtime creation and manipulation of images.",
	"ExperienceNotificationService": "Service containing methods to validate users and prompt them to enable experience notifications.",
	"EditableMesh": "Object which allows for the runtime creation and manipulation of meshes.",
	"DragDetector": "Instance which facilitates and encourages interaction with 3D objects in an experience.",
	"DraggerService": "A service that centralizes the global dragger settings that Studio's dragging tools read so they move, snap, and highlight objects consistently.",
	"DraftsService": "A Studio service that manages script drafts in a Team Create session with collaborative editing enabled.",
	"EchoSoundEffect": "Adds delayed repetitions of a sound with diminishing volume.",
	"Dragger": "A helper object used to create tools that can drag parts.",
	"DoubleConstrainedValue": "An instance which is used to create a number value which can never be less than the MinValue or more than the MaxValue.",
	"Explosion": "Applies force to BasePart within the explosion's Explosion.BlastRadius.",
	"FaceControls": "The FaceControls object defines a set of properties for controlling the facial expressions of a Dynamic Head.",
	"DynamicRotate": "The base class for classic motor joints.",
	"EulerRotationCurve": "Represents a 3D rotation curve through a group of three FloatCurve.",
	"EncodingService": "Service providing common encoding, hashing, and compression methods.",
	"EqualizerSoundEffect": "Controls the volume of incoming audio across three frequency ranges.",
	"Frame": "A GuiObject that renders as a plain rectangle, generally used as a container.",
	"ForceField": "Protects a Humanoid from taking damage dealt through the Humanoid:TakeDamage() method and protects BasePart from having their joints broken due to an Explosion.",
	"FormFactorPart": "The FormFactorPart class is an abstract class.",
	"Folder": "A simple container used to hold and organize Roblox instances.",
	"Fire": "A preconfigured particle emitter with the visual aesthetic of fire.",
	"FlangeSoundEffect": "Creates a sweeping or swooshing effect on a sound.",
	"FileMesh": "The FileMesh object applies a mesh to a BasePart when parented to it.",
	"Flag": "The Flag object helps you make 'capture the flag' style games.",
	"FloatCurve": "A sorted list of time-value pairs that define a curve.",
	"Feature": "The base class for the legacy motor system.",
	"FlagStand": "The FlagStand object helps you make 'capture the flag' style games.",
	"FlagStandService": "An internal service responsible for handling the now deprecated FlagStand and Flag objects.",
	"FloorWire": "A FloorWire attempts to make a wire from two of its properties: FloorWire.From and FloorWire.From, which both need to be set to a BasePart.",
	"FaceInstance": "An abstract class from which the Decal and Texture classes inherit.",
	"FluidForceSensor": "A SensorBase that outputs FluidForceSensor.Force, FluidForceSensor.Torque and FluidForceSensor.CenterOfPressure.",
	"File": "An asset loaded from a file on disk.",
	"FriendPages": "A special version of Pages that contains information about a player's friends.",
	"GlobalDataStore": "An object that exposes methods to access a single data store.",
	"GamepadService": "The GamepadService is internally responsible for handling inputs from various controllers, such as Xbox One or PlayStation DualShock controllers.",
	"FunctionalTest": "Deprecated container for automated test scripts; use TestService instead.",
	"Geometry": "An internal Roblox service which cannot be used by developers.",
	"Glue": "Glue is a type of joint that can break when enough force is applied.",
	"GenerationService": "Service that allows developers to generate 3D objects from text prompts.",
	"GenericSettings": "The abstract class for settings database classes.",
	"GroundController": "The ControllerBase that moves a ControllerManager character while it is walking or standing on the ground.",
	"FriendService": "An internal service which is used to send, cancel, accept and decline friend requests in-game.",
	"GetTextBoundsParams": "Use with TextService:GetTextBoundsAsync() to measure the size of text.",
	"GameSettings": "A container for miscellaneous in-game options.",
	"GlobalSettings": "Collection of menu settings for Roblox Studio.",
	"GeneratedFolder": "A container that stores ProceduralModel generation results.",
	"GeometryService": "Service containing geometric operations.",
	"GamePassService": "A service associated with the legacy game pass system.",
	"GuiObject": "An abstract class for all 2D user interface objects.",
	"Handles": "Places 3D handles around any object that its Handles.Adornee is set to.",
	"GuiButton": "An abstract class for interactive 2D user interface elements.",
	"GuiService": "Offers numerous properties and methods for working with GuiObject, player preferences, and other UI‑related tasks.",
	"GuiBase2d": "An abstract class inherited by 2D GuiObject.",
	"GroupService": "GroupService is a service that allows developers to fetch information about a Roblox group from within a game.",
	"HapticService": "Provides haptic feedback to controllers and devices.",
	"GuidRegistryService": "An internal service, whose functionality is not accessible to developers.",
	"HandlesBase": "An abstract class for Handle objects, such as ArcHandles and Handles.",
	"HandleAdornment": "An abstract class inherited by 3D handle adornments.",
	"GuiBase3d": "An abstract class for 3D GUI elements that are rendered in the world.",
	"GuiLabel": "An abstract class for non-interactive 2D user interface elements.",
	"GuiBase": "GuiBase is an abstract class which most graphical user interface objects inherit from.",
	"Hat": "A deprecated accessory container superseded by Accessory.",
	"HapticEffect": "An object that provides waveform-based haptic feedback (vibrations and rumbles) on supported controllers and mobile devices.",
	"GuiMain": "The original name of the ScreenGui.",
	"HttpService": "Allows sending HTTP requests and provides various web-related and JSON methods.",
	"HumanoidRigDescription": "Stores the joint mapping, T-pose, and per-joint properties for a 22-joint bipedal character rig.",
	"IKControl": "Specifies a control to generate a procedural animation pose using Inverse Kinematics.",
	"HumanoidController": "A Controller held within ControllerService that translates player input into movement for the user's character Humanoid.",
	"Hint": "A Hint is an object that creates a small black bar at the very top of the screen with text.",
	"HeightmapImporterService": "A Studio-only service that backs the Terrain Editor's heightmap import tool, converting heightmap and colormap images into voxel Terrain.",
	"HingeConstraint": "Constrains its attachments to rotate about a single axis.",
	"Humanoid": "A special object that gives models the functionality of a character.",
	"HiddenSurfaceRemovalAsset": "Stores the precomputed hidden surface removal (HSR) data for a layered-clothing wrap, marking the mesh faces that are hidden by higher clothing layers so the engine can cull them.",
	"HumanoidDescription": "Describes the appearance of a Humanoid character including body parts, accessories, colors, scales, animations, and emotes.",
	"HeapProfilerService": "Generates and retrieves Luau heap memory profiles from the client and server Luau virtual machines for memory debugging.",
	"HSRDataContentProvider": "An internal service that fetches, parses, and caches hidden surface removal (HSR) data for layered clothing; cannot be used by developers.",
	"Hopper": "Hopper is the original name of the StarterPack service.",
	"Highlight": "A visual effect which you can use to call attention to a specific object within an experience.",
	"InsertService": "Used to insert assets from the Roblox website.",
	"InputObject": "An object created when an input begins that describes a particular user input.",
	"ILegacyStudioBridge": "Internal Studio-only base interface for a Studio bridge service.",
	"Instance": "`Instance` is the base class for all classes in the Roblox class hierarchy which can be part of the DataModel tree.",
	"ImageButton": "A 2D user interface element that displays an interactive image.",
	"IntersectOperation": "Result of parts that have been intersected into a single solid model.",
	"InputBinding": "Defines which hardware binding should trigger the parent InputAction.",
	"ImageHandleAdornment": "An image handle that can be adorned to a BasePart.",
	"ImageLabel": "A 2D user interface element that displays a single non-interactive image.",
	"IntConstrainedValue": "An IntConstrainedValue is used to store a value which can never be less than MinValue and can never be more than MaxValue.",
	"InputContext": "Collection of actions which holds related actions and defines how they interact with other contexts/actions.",
	"InputAction": "Defines a gameplay action mechanic.",
	"IncrementalPatchBuilder": "Builds signed incremental patches for hot-reloading a running client from script changes detected by a separate file watcher.",
	"InputActionLabel": "A GuiObject that automatically displays the keybinding for an action as text or an image.",
	"InstanceAdornment": "A base class for all objects that adorn Instance classes.",
	"InstanceFileSyncService": "A service for interacting with file sync from a plugin.",
	"KeyframeSequenceProvider": "Provides functions to load and preview KeyframeSequence.",
	"LayerCollector": "The base class of 2D UI containers which render GuiObject in layers.",
	"KeyframeSequence": "This object stores all of the Keyframe and other data for the animation.",
	"KeyboardService": "Service that maintains keyboard state, TextBox focus, and clipboard access; scripts read keyboard input through UserInputService instead.",
	"KeyframeMarker": "An instance meant to represent an event that will eventually be fired when a Keyframe is hit.",
	"Keyframe": "A Keyframe holds the Pose applied to joints in a Model at a given point of time in an animation.",
	"Lighting": "The `Lighting` service controls global lighting in an experience.",
	"LineForce": "Applies a force along the theoretical line connecting its two Attachment.",
	"JointInstance": "The base class for joints.",
	"InventoryPages": "A special version of Pages that contains information about a specific category of a user's inventory.",
	"IntValue": "A container object for a single integer.",
	"LinearVelocity": "Applies force on an assembly to maintain a constant linear velocity.",
	"LineHandleAdornment": "A line-shaped handle that can be adorned to a BasePart.",
	"Light": "Light is a root class for dynamic lighting related objects.",
	"JointsService": "A service that stores joints created by surface connections.",
	"LocalizationService": "Handles automated translation.",
	"MaterialVariant": "Represent a variant of a Material.",
	"MarketplaceService": "The service responsible for in-experience transactions.",
	"MakeupDescription": "Describes the appearance of a makeup item for the HumanoidDescription.",
	"LocalizationTable": "A LocalizationTable is a database of translations.",
	"LocalScript": "An object that contains and runs Luau code on the client (player's device) instead of the server.",
	"LoginService": "An internal service whose functionality is not available to developers.",
	"LuaSettings": "Settings related to how the engine handles Luau, its dialect of Lua.",
	"ManualWeld": "Holds two parts together and functions identically to Weld.",
	"LogService": "A service that allows you to read outputted text.",
	"MarkerCurve": "Represents a list of strings markers in chronological order.",
	"MatchmakingService": "The service responsible for managing custom matchmaking data.",
	"LuaWebService": "An internal service, which is responsible for retrieving HTTP data from websites.",
	"LuaSourceContainer": "The base class for all objects which contain Luau code.",
	"ManualSurfaceJointInstance": "ManualSurfaceJointInstance is the base class for ManualGlue and ManualWeld.",
	"ManualGlue": "ManualGlue is a joint created in a similar manner to the ManualWeld class.",
	"MaterialService": "The game service responsible for managing materials.",
	"MemoryStoreHashMap": "Provides access to a hash map within MemoryStoreService.",
	"ModuleScript": "A script type that runs once when `Global.LuaGlobals.require()` is called with it.",
	"MeshPart": "A form of BasePart that includes a physically simulated custom mesh.",
	"MemoryStoreSortedMap": "Provides access to a sorted map within MemoryStoreService.",
	"MemoryStoreService": "Exposes methods to access specific primitives within MemoryStore.",
	"Model": "Models are container objects, meaning they group objects together.",
	"Message": "Fills the entire screen with a semi-transparent grey background, with centered text in the middle of the screen.",
	"ModerationService": "Server-side service for submitting player captures to content moderation review and receiving the results asynchronously.",
	"MemoryStoreHashMapPages": "A special type of Pages object whose pages contain key-value pairs from a MemoryStoreHashMap.",
	"MLService": "A service that runs in-engine machine learning inference by loading model bundles and creating inference sessions.",
	"MemoryStoreQueue": "Provides access to a queue within MemoryStore.",
	"MLSession": "A machine-learning inference session that wraps a single loaded model and runs it through MLSession:ForwardAsync().",
	"Motor": "Makes a movable JointInstance between two parts.",
	"MeshContentProvider": "An internal Roblox service that is responsible for fetching, parsing and caching meshes.",
	"MessagingService": "Allows servers of the same experience to communicate with each other.",
	"MemStorageConnection": "Represents a live binding created by `Bind()` on MemStorageService that runs a callback whenever a memory-storage key changes.",
	"NoCollisionConstraint": "An instance used to prevent collisions between two specific parts.",
	"Motor6D": "Creates an animatable joint between two BasePart.",
	"NumberPose": "Holds the value applied to a specific FACS control.",
	"Object": "`Object` is the base class for all classes in the Roblox class hierarchy.",
	"ObjectValue": "A container object for a reference to another instance.",
	"NetworkSettings": "Settings related to networked engine behaviors.",
	"NetworkPeer": "The `NetworkPeer` object is the most basic class of the network objects.",
	"NetworkClient": "A service that manages a network connection's properties server.",
	"NumberValue": "A container object for a single double-precision floating point number.",
	"MouseService": "Engine service that manages mouse cursor rendering, mouse lock behavior, the cursor-icon stack, delta sensitivity, and mouse position, delta, and button tracking.",
	"NetworkServer": "A server-side service that manages all NetworkReplicator instances and handles incoming client connections.",
	"NetworkReplicator": "An object which handles the replication of other objects either from the server to the client, or from the client to the server.",
	"NegateOperation": "Result of a part that has been negated for use in solid modeling.",
	"NetworkMarker": "The NetworkMarker is used to tell the client when the server has finished loading the world for the client.",
	"Mouse": "Legacy object that contains members useful for pointer input.",
	"PathfindingLink": "Connects two locations which otherwise by default are unconnected.",
	"OpenCloudApiV1": "Deprecated Open Cloud API surface for in-experience cloud operations such as user notifications.",
	"PartOperation": "An abstract class that all parts based on solid modeling inherit from.",
	"PartAdornment": "An abstract class for GUI elements that are adorned to (displayed as attached to) objects deriving from BasePart.",
	"OutfitPages": "The `OutfitPages` class is used in the case of iterating over a user's outfits.",
	"PackageService": "Manages Roblox Studio packages, tracking their metadata and versions and handling updates to package contents.",
	"Path": "Stores the result of paths created by PathfindingService:CreatePath().",
	"ParticleEmitter": "A special object that emits customizable 2D particles into the world.",
	"Pants": "Displays a Pants texture from the Roblox website to display on a Humanoid rig.",
	"Pages": "An abstract class for pages objects.",
	"PackageLink": "Links a DataModel instance to a corresponding asset in the cloud.",
	"OrderedDataStore": "A GlobalDataStore that also allows for ordered data store entries.",
	"Part": "A common type of BasePart that comes in different primitive shapes.",
	"PartOperationAsset": "An internal service which cannot be used by developers.",
	"Path2D": "Represents a 2D cubic spline path that renders a stroked curve under any GuiObject.",
	"OpenCloudService": "Deprecated.",
	"PathfindingModifier": "Modifiers used to represent space that has a higher or lower cost to be traversed when creating paths using PathfindingService.",
	"PlayerGui": "A container that holds a player's UI.",
	"PhysicsSettings": "Lets you view debugging features in Roblox's physics engine, found under the Physics tab in Studio's settings menu.",
	"PhysicsService": "Service that provides methods for creating and managing collision groups, which control whether sets of BasePart collide with each other.",
	"Plugin": "The main object responsible for creating custom Studio widgets, toolbars, buttons, and other plugin UI elements.",
	"PitchShiftSoundEffect": "Adjusts the pitch of a sound without changing its playback speed.",
	"PathfindingService": "Used to find logical paths between two points.",
	"Plane": "Constrains Attachment0 and Attachment1 such that both points lie in a plane with origin at Attachment0's position and unit normal vector equal to Attachment0's primary axis.",
	"PlayerMouse": "The PlayerMouse behaves identically to the Mouse object that is obtained using Tool.Equipped.",
	"PlaneConstraint": "Moves its attachments into a position/orientation along a plane whose normal vector is the primary axis of Constraint.Attachment0.",
	"Platform": "Historically a form of Seat that wouldn't place the player in a sitting pose.",
	"Players": "A service that contains presently connected Player objects.",
	"Player": "An object that represents a presently connected client to the experience.",
	"PlayerListConfiguration": "Controls the built-in player list, the CoreGui element that displays the players currently in the experience.",
	"PlayerViewService": "Provides a way to get additional information about a player's view.",
	"PlayerScripts": "A container for client-side scripts to be run inside Player objects within the Players service.",
	"PluginAction": "Represents a generic performable action in Roblox Studio that can optionally be bound to a keyboard shortcut.",
	"PointLight": "A light source that emits illumination from a single point.",
	"PluginDragEvent": "Provides information about an in-progress drag for the drag events that plugins can respond to.",
	"PluginManagerInterface": "The singleton object returned by the global `PluginManager()` function, exposing a small set of legacy Studio plugin utilities.",
	"PluginConnectionService": "This service is used by plugins to communicate with other instances of themselves running in other data models.",
	"PluginGuiService": "A service that stores PluginGui objects to be displayed in Roblox Studio.",
	"PluginConnection": "Encapsulates a connection between the current data model and another for plugin communication.",
	"PluginCapabilities": "Declares a plugin's capabilities (the data models it targets and the permissions it requests) through a JSON manifest.",
	"PluginMouse": "The PluginMouse object gives Plugin access to the mouse.",
	"PluginToolbar": "A toolbar created by Plugin:CreateToolbar() that groups PluginToolbarButton in the Studio ribbon.",
	"PluginToolbarButton": "A button on a PluginToolbar in the Studio ribbon, created by PluginToolbar:CreateButton(), that fires PluginToolbarButton.Click when pressed.",
	"PluginManager": "A deprecated singleton that was previously required to create plugins.",
	"PluginGui": "An abstract base class for GUIs that display GuiObject in Roblox Studio widgets.",
	"PluginManagementService": "Studio service that manages installed plugins; not intended for creator scripts or plugins.",
	"PluginDebugService": "A service that holds the debuggable Plugin instances that are currently being debugged in Studio, parenting them into the data model.",
	"PluginMenu": "A context menu that can be shown in Studio.",
	"PolicyService": "Helps you query information regarding policy compliance for players around the world based on age range, location, and platform type.",
	"PoseBase": "Base class of all 'Pose Instance' objects.",
	"PVInstance": "Abstract class for all objects that have a physical location in the world.",
	"ProximityPrompt": "An object that lets you prompt players to interact with an object in the 3D world.",
	"Pose": "Holds the CFrame applied to the Motor6D connected to its associated BasePart.",
	"PointsService": "This service controls the points award system used to showcase a player's achievements and participation throughout Roblox.",
	"PrismaticConstraint": "Constraint which creates a rigid joint between two Attachment, allowing them to slide along one axis but not rotate.",
	"ProceduralModel": "Procedural models support edit-time procedural generation.",
	"PVAdornment": "An abstract class of which the inheritors can be adorned to objects of the PVInstance class.",
	"ProximityPromptService": "Allows developers to interact with ProximityPrompt objects in a global way.",
	"PostEffect": "Abstract base class for post-processing effects.",
	"PublishService": "A service that centralizes uploading assets to Roblox, including publishing cage mesh edits and creating assets or asset versions.",
	"RecommendationPages": "A special version of the Pages class returned by RecommendationService.GenerateItemListAsync.",
	"RayValue": "A container object for a single Ray.",
	"PyramidHandleAdornment": "A pyramid-shaped handle that can be adorned to a BasePart.",
	"ProcessInstancePhysicsService": "An internal engine service that generates collision geometry (physics data) for MeshPart and PartOperation instances that need new physics.",
	"ReflectionMetadataClass": "Registers information about a class, and its members.",
	"ReflectionMetadataCallbacks": "Acts as a Folder containing information about callbacks for a ReflectionMetadataClass, and should be parented to it.",
	"ReflectionMetadataEnums": "Acts as a Folder for ReflectionMetadataEnum objects.",
	"RecommendationService": "A service that provides an interface for you to manage and display personalized content recommendations.",
	"ReflectionMetadataFunctions": "Acts as a Folder containing information about functions for a ReflectionMetadataClass, and should be parented to it.",
	"ReflectionMetadataProperties": "Acts as a Folder containing information about properties for a ReflectionMetadataClass, and should be parented to it.",
	"ReflectionService": "A service that allows scripts to query the engine's API at runtime for information about classes, properties, methods, and events.",
	"ReflectionMetadataEvents": "Acts as a Folder containing information about events for a ReflectionMetadataClass, and should be parented to it.",
	"ReflectionMetadata": "A currently unused object whose functionality was split into ReflectionMetadataClasses and ReflectionMetadataEnums.",
	"ReflectionMetadataYieldFunctions": "Acts as a Folder containing information about yielding functions for a ReflectionMetadataClass, and should be parented to it.",
	"ReflectionMetadataClasses": "An internal object which cannot be used by developers.",
	"RemoteCommandService": "Team Create service that executes Luau commands sent from a Studio client on the collaborative editing server and relays their output back to that client.",
	"ReflectionMetadataItem": "Acts as abstract properties for generic information about Classes, Members, Enums, and EnumItems.",
	"ReflectionMetadataEnum": "Registers information about an Enum and its EnumItems.",
	"ReflectionMetadataEnumItem": "Contains information about a specific EnumItem embedded within an Enum.",
	"ReflectionMetadataMember": "An internal object which cannot be used by developers.",
	"RotationCurve": "Represents a sequence of rotations and the interpolation curve between them.",
	"RigidConstraint": "Creates a rigid connection between two Attachment or Bone.",
	"RemoteFunction": "An object which facilitates synchronous, two-way communication across the client-server boundary.",
	"ReverbSoundEffect": "Reverberates audio, simulating the effect of bouncing off walls in a room.",
	"RunningAverageItemDouble": "Measures the runtime average of a **double** value.",
	"RemoteDebuggerServer": "Studio service that runs the server side of Luau remote debugging over DAP; not created during normal script execution.",
	"RotateV": "Joins two parts and allows rotation driven by angular velocity from the Motor surface type.",
	"RocketPropulsion": "Applies a force so that an assembly follows and faces a target part.",
	"RodConstraint": "Keeps two attachments separated by its defined RodConstraint.Length.",
	"ReplicatedFirst": "A container whose contents are replicated to all clients (but not back to the server) first before anything else.",
	"ReplicatedStorage": "A container service for objects that are replicated to all clients.",
	"RenderSettings": "A singleton settings class that exposes rendering configuration for graphics quality, framerate management, and debug visualization in Roblox Studio.",
	"RopeConstraint": "Simulates rope dynamics, preventing two attachments from separating further than a defined length.",
	"RemoteEvent": "An object which facilitates asynchronous, one-way communication across the client-server boundary.",
	"ScrollingFrame": "`ScrollingFrame` is a special Frame type with built-in scrolling interactivity and different ways to customize how the scrolling works.",
	"Script": "An object that contains and runs Luau code on the server.",
	"ScreenGui": "Primary container of on-screen 2D user interface elements.",
	"Seat": "A type of BasePart that characters can 'sit' in.",
	"ScriptProfilerService": "A service that captures sampling-based profiles of Luau script execution on the server or on a client.",
	"ScriptEditorService": "This service is used for interacting with ScriptDocument instances.",
	"ScreenshotHud": "A 2D user interface that allows users to capture and save screenshots to their local device.",
	"RunningAverageItemInt": "Measures the runtime average of an **integer** value.",
	"ScriptService": "An unimplemented service that has zero functionality, in a similar manner to the `LocalWorkspace` service.",
	"ScreenshotCapture": "A child class of Capture for screenshots.",
	"ScriptDocument": "Represents the ephemeral state of an open document in the Studio Script Editor, providing APIs for reading and editing code.",
	"ScriptContext": "A service that manages the execution of all BaseScript objects.",
	"RunService": "Service responsible for all runtime activity and progression of time.",
	"RunningAverageTimeIntervalItem": "Measures the runtime average of a time interval value.",
	"ScriptDebuggerService": "Provides programmatic breakpoint management, execution control, and runtime inspection of Luau scripts during a playtest.",
	"Selection": "The Selection service controls the Instance that are selected in Roblox Studio.",
	"Shirt": "Displays a shirt texture on a Humanoid rig.",
	"ServerScriptService": "A container service for server-only Script objects.",
	"SerializationService": "Serializes and deserializes Instance to and from the `.rbxm` format.",
	"ServerStorage": "A container whose contents are only accessible on the server.",
	"SelectionLasso": "Abstract class for SelectionPartLasso and SelectionPartLasso.",
	"SelectionBox": "Renders a 3D box around its PVAdornment.Adornee.",
	"SharedTableRegistry": "Provides a global registry of named SharedTable objects.",
	"SelectionPartLasso": "An instance used to display a \"lasso\" between a Humanoid Torso and a BasePart.",
	"SelectionSphere": "Renders a 3D sphere around its PVAdornment.Adornee.",
	"SensorBase": "An abstract class for various sensor instance types.",
	"SelectionHighlightManager": "Studio service that draws selection outline highlights for the local user's selection and for Team Create collaborators' selections.",
	"ServerReplicator": "The server-side NetworkReplicator that manages replication of data model changes between the server to a single connected client.",
	"SelfViewConfiguration": "Controls the built-in self view, the CoreGui element that shows a player a preview of their own character within an experience.",
	"ServiceProvider": "A ServiceProvider is an abstract class, which stores, and provides certain singleton classes, depending on what inherited class you are using its members with.",
	"Sound": "An object that emits sound.",
	"SlimContentProvider": "A service that fetches and caches SLIM (Scalable Lightweight Interactive Models) asset content representations for model rendering.",
	"SoundService": "A service that determines various aspects of how the audio engine works.",
	"SkateboardController": "Translates player input into throttle and steer axis values for a SkateboardPlatform.",
	"SoundEffect": "SoundEffect is the base class that all other sound effects derive from.",
	"ShirtGraphic": "Applies a texture to the front surface of a character's torso, used to display t-shirts.",
	"Sparkles": "A particle emitter with the visual aesthetic of sparkles.",
	"Smoke": "A particle emitter with the visual aesthetic of smoke.",
	"Snap": "Holds two parts together and functions identically to Weld.",
	"SlidingBallConstraint": "The base class for constraints that allow their attachments to slide along an axis but not rotate.",
	"SoundGroup": "A SoundGroup is used to manage the volume and sound effects on multiple Sound at once.",
	"SkateboardPlatform": "A SkateboardPlatform can be used to create a skateboard.",
	"Sky": "Changes the default appearance of the experience's sky.",
	"Skin": "Historically changed the colors of body parts to match the Skin.SkinColor property.",
	"SolidModelContentProvider": "An internal service which serves no functionality to developers.",
	"SocialService": "Facilitates social functions that impact relationships made on the Roblox platform.",
	"SpawnLocation": "SpawnLocation, or \"spawns\" determine where a Player respawns when they die.",
	"StarterGui": "A container for LayerCollector objects to be copied into the PlayerGui of Player.",
	"SpecialMesh": "The SpecialMesh object applies a mesh to a BasePart depending on the SpecialMesh.MeshType property.",
	"StarterPlayer": "A service which allows the defaults of properties in the Player object to be set.",
	"SpringConstraint": "Simulates spring and damper behavior between two attachments.",
	"StandardPages": "A generic Pages object that can contain variable data depending on the method that returned it.",
	"SpawnerService": "An internal service that is responsible for the behavior of SpawnLocation.",
	"Stats": "Performance metrics for a game.",
	"StarterPack": "A container whose contents are copied into each player's Backpack when their player character spawns.",
	"StarterGear": "If the game allows gear, `StarterGear` is a container automatically inserted into each Player object when the player joins the game.",
	"SphereHandleAdornment": "A sphere-shaped handle that can be adorned to a BasePart.",
	"StarterPlayerScripts": "A container for objects to be copied to a Player's PlayerScripts when they join a game.",
	"StarterCharacterScripts": "Stores instances to be parented to a player's character when it spawns.",
	"StatsItem": "A single performance metric.",
	"SpotLight": "A light source that emits light directionally in the shape of a cone with a spherical base.",
	"StandalonePluginScripts": "A container for Script that run only in the standalone plugin DataModel at Roblox Studio startup.",
	"StudioTestService": "Service allowing plugins to automate and customize Test and Run mode testing.",
	"StudioScreenshotCapture": "Represents a single screenshot captured from Studio, exposing the resulting image buffer and the parameters the capture was taken with.",
	"StudioDeviceSimulatorService": "Service allowing you to control Studio's Device Simulator.",
	"Studio": "Represents Roblox Studio's script editor settings.",
	"StudioTheme": "A collection of colors that make up a Roblox Studio theme, letting a plugin query the color of a Studio UI element for the theme the user currently has active.",
	"StudioCaptureService": "A Studio-only service that lets plugins capture screenshots of the active place's 3D viewport.",
	"StyleLink": "Links a StyleSheet to the instance tree whose root is the parent of the `StyleLink`.",
	"StudioService": "Provides access to configuration of Roblox Studio and allows importing files from the user's file system.",
	"StyleQuery": "Instance used to set conditions such as `\"MaxSize\"` and `\"PreferredInput\"` for a StyleRule.",
	"StyleBase": "The base class for StyleSheet and StyleRule.",
	"StyleSheet": "Aggregates StyleRule and can be linked to DataModel trees to apply style properties to instances.",
	"StopWatchReporter": "A service that times named tasks and reports their durations, classified by device platform and country code.",
	"StyleRule": "Defines style properties which override properties on the instances affected by the StyleRule.Selector property.",
	"StyleDerive": "When parented to a StyleSheet, references another StyleSheet from which the parent inherits StyleRule and token definitions.",
	"StringValue": "A container object for a single string.",
	"Status": "An unfinished object which offers no functionality to developers.",
	"SurfaceAppearance": "An object that allows developers to override the appearance of a MeshPart with advanced graphics options.",
	"SunRaysEffect": "Renders dynamic rays from the sun.",
	"SurfaceGui": "Container for GuiObjects that are rendered on the surface of a part.",
	"Teams": "The Teams service holds a game's Team objects.",
	"TeleportOptions": "Optional input arguments to the TeleportService:TeleportAsync() function.",
	"TaskScheduler": "Collection of settings for the _Task Scheduler_ feature.",
	"Terrain": "`Terrain` lets you to create dynamically morphable environments.",
	"SurfaceGuiBase": "Base class for containers that render GuiObject onto a face of a BasePart in the 3D world.",
	"TeleportAsyncResult": "The return structure of the `TeleportAsync` function call.",
	"Team": "The Team class represents a faction in a Roblox place.",
	"SurfaceSelection": "Highlights a face of a surface in a configurable color.",
	"SwimController": "The ControllerBase that moves a ControllerManager character while it is swimming.",
	"TeleportService": "Enables transporting Player between places and servers.",
	"TerrainDetail": "Determines appearance of a certain terrain face direction.",
	"TerrainRegion": "An object that stores a chunk of terrain voxel data, produced by Terrain:CopyRegion() and consumed by Terrain:PasteRegion().",
	"SurfaceLight": "A light source that emits illumination of a specified color and brightness from a face for a specified range.",
	"TextButton": "A 2D user interface element that displays interactive text.",
	"TextService": "Service internally responsible for handling the display of text.",
	"TextBox": "A 2D user interface element that displays player-editable text.",
	"TextChatMessage": "A data object representing a text chat message.",
	"TextChannel": "Represents a text chat channel.",
	"TextFilterResult": "Represents the result of a call to TextService:FilterStringAsync(), used to distribute a filtered string accordingly.",
	"TestService": "A service used by Roblox to run controlled tests of the engine.",
	"TextGenerator": "Gives access to a large language model for text generation.",
	"TextChatCommand": "Represents a text chat command.",
	"TextLabel": "A 2D user interface element that displays non-interactive text.",
	"TextChatConfigurations": "The parental class of all text chat configurations.",
	"TextChatService": "A service handling in-experience text chat.",
	"TextChatMessageProperties": "Overrides TextChatMessage properties when returned by callbacks defined in TextChatService.OnIncomingMessage or TextChannel.OnIncomingMessage.",
	"TextBoxService": "A service that manages a user's TextBox state during gameplay.",
	"TextFilterTranslatedResult": "Holds the filtered source text and its filtered translations produced by TextService:FilterAndTranslateStringAsync().",
	"Translator": "The role of a Translator is to manufacture/return strings localized for the viewing player.",
	"Trail": "Used to create a trail effect between two attachments.",
	"TrussPart": "Similar to a Part but with a different visual TrussPart.Style and the important distinction that default characters are able to climb it.",
	"TotalCountTimeIntervalItem": "Measures a total-count-over-time interval.",
	"Tool": "An object, such as a weapon, that can be equipped by a Humanoid.",
	"TriangleMeshPart": "Abstract intermediate class that manages physical geometry properties for PartOperations and MeshParts.",
	"Texture": "Applies a repeating image texture to the face of a parent BasePart.",
	"TimerService": "An internal service responsible for scheduling timed events.",
	"Tween": "The Tween object controls the playback of an interpolation.",
	"TextSource": "Represents a speaker in a TextChannel.",
	"TorsionSpringConstraint": "A rotational spring that opposes the angular motion between two axes.",
	"TweenBase": "Abstract base class for in-between interpolation handlers.",
	"Torque": "Applies constant torque to an assembly from its center of mass.",
	"TouchTransmitter": "An internal object used by networking and replication code to transmit BasePart.Touched and BasePart.TouchEnded events.",
	"TouchInputService": "An internal service responsible for touch inputs on mobile devices.",
	"TremoloSoundEffect": "Creates a trembling effect on a sound by varying the volume of the sound up and down.",
	"UIScale": "An object that acts as a multiplier for the size of the parent UI element's scale.",
	"TweenService": "Used to create Tween which interpolate, or tween, the properties of instances.",
	"UILayout": "The base class for UI layout classes.",
	"UIGradient": "Applies a color and transparency gradient to the parent GuiObject.",
	"UIGridStyleLayout": "The base class for grid style UI layouts.",
	"UIPageLayout": "Positions sibling UI elements as full-size pages in a single row or column that users can scroll or animate through one page at a time.",
	"UIConstraint": "The base class for UI constraint classes.",
	"UICorner": "UI modifier which applies deformation to corners of its parent GuiObject.",
	"UIPadding": "Applies padding to the borders of the parent GuiObject.",
	"UIDragDetector": "Instance which facilitates and encourages interaction with UI elements in an experience.",
	"UIComponent": "A base class for UI constraint and layout classes.",
	"UIFlexItem": "Defines flex behavior for a GuiObject within a UIListLayout.",
	"UIBase": "UIBase is the base class for UI layout and constraint classes.",
	"UIListLayout": "Positions sibling UI elements in rows or columns within the parent UI container.",
	"UIAspectRatioConstraint": "Ensures the parent UI element maintains a particular aspect ratio.",
	"UIGridLayout": "Positions sibling UI elements by filling rows using the space of the parent UI element.",
	"UserService": "A service that handles queries regarding users on the Roblox platform.",
	"UserGameSettings": "`UserGameSettings` is a singleton class found inside of the UserSettings singleton.",
	"UnreliableRemoteEvent": "An object which facilitates asynchronous, unordered and unreliable, one-way communication across the client-server boundary.",
	"UserInputService": "`UserInputService` is primarily used to detect the input types available on a user's device, as well as detect input events.",
	"UnionOperation": "Result of parts that have been joined together into a single solid model.",
	"Vector3Curve": "Represents a 3D vector curve, grouping three FloatCurve instances.",
	"UISizeConstraint": "Ensures a GuiObject does not become larger or smaller than the constraint's maximum size or minimum size.",
	"UIStroke": "Applies an outline to text or a UI border.",
	"UserSettings": "A singleton object that houses basic user settings, which persist across all games on Roblox.",
	"ValueCurve": "A sorted list of time-value pairs that define a curve.",
	"UniqueIdLookupService": "Team Create service that maps Instance.UniqueId to and from RFC-4122 strings; not for experience scripts.",
	"UITableLayout": "Lays out sibling UI elements and their child UI elements as rows/columns and cells in a table.",
	"UIShadow": "Renders a shadow below the parent UI instance.",
	"UITextSizeConstraint": "Ensures that the size of text rendered by certain GuiObject classes lies within the range described by UITextSizeConstraint.MaxTextSize and UITextSizeConstraint.MinTextSize.",
	"ValueBase": "Base class of all \"value instance\" objects.",
	"UniversalConstraint": "Ensures two axes on two bodies remain perpendicular.",
	"VideoFrame": "A GUI object that renders a rectangle, like a Frame does, with a moving video image.",
	"ViewportFrame": "GuiObject that renders 3D objects inside its bounds.",
	"VirtualInput": "Simulates mouse, keyboard, and pointer input as if it were performed by a real player.",
	"VideoCaptureService": "Service that manages camera capture for features such as avatar facial-animation tracking.",
	"VectorForce": "Applies constant force to an assembly.",
	"VehicleController": "An object responsible for translating a seated player's directional input into throttle and steering for a VehicleSeat.",
	"VideoService": "An internal service that offers no functionality to developers.",
	"VideoSampler": "An object for sampling frames from video content.",
	"VirtualUser": "VirtualUser is a service that allows you to record the inputs of a user, and then play it back to a limited extent.",
	"VideoPlayer": "Used to play video assets.",
	"VelocityMotor": "A Motor-like JointInstance that forms its connection using a MotorFeature and a Hole.",
	"VehicleSeat": "A seat object that can be used to control a vehicle.",
	"Vector3Value": "A container object for a single Vector3 value.",
	"VideoCapture": "A child class of Capture for videos.",
	"VirtualInputManager": "An internal service that offers no functionality to developers.",
	"VideoDisplay": "A GUI object that displays video content from a connected VideoPlayer.",
	"VoiceChatService": "**VoiceChatService** is responsible for voice chat's high-level functionality.",
	"WrapDeformer": "Allows for the real-time deformation of a MeshPart.",
	"WireframeHandleAdornment": "Renders a wireframe adornment consisting of one or more lines onto a BasePart (including Terrain) or into the Workspace.",
	"WedgePart": "A type of BasePart that has a wedge shape.",
	"WrapLayer": "The WrapLayer object defines a 3D accessory's inner and outer surfaces and other properties related to layering accessories.",
	"WorldRoot": "Base class for handling physics simulation and 3D spatial queries.",
	"Wire": "Connects one or more Instance to form a processing graph of their streams.",
	"WebStreamClient": "Maintains a streaming connection.",
	"Workspace": "`Workspace` houses 3D objects which are rendered to the 3D world.",
	"WeldConstraint": "Connects two BasePart together such that their relative position and orientation remain the same.",
	"Weld": "Holds two BasePart together in a fixed relative position, regardless of whether they're touching.",
	"VisibilityCheckDispatcher": "Service that schedules and runs viewability checks for immersive ad instances in a place.",
	"WorldModel": "Extends limited physics to its children.",
	"Visit": "The Visit service is a backend service used by Roblox.",
	"VRService": "Service responsible for handling interactions between Roblox and Virtual Reality (VR).",
	"WrapTarget": "The WrapTarget object defines a target.",
	"WrapTextureTransfer": "WrapTextureTransfer allows a parent Decal to be wrapped around its parent MeshPart based on the cage of its WrapTarget."
};

/** One sentence per datatype, by name. */
export const DATATYPE_SUMMARIES: Record<string, string> = {
	"AdReward": "A reward that can be granted to users upon watching rewarded video ads.",
	"Axes": "The `Axes` data type is for the ArcHandles class to control which rotation axes are currently enabled.",
	"Content": "Represents a reference to asset content stored externally or as an object within the place.",
	"Collection": "A live, query-based group of instances returned by CollectionService:CreateCollection().",
	"Enum": "A data type that represents an individual enum.",
	"DockWidgetPluginGuiInfo": "Describes details for a DockWidgetPluginGui.",
	"Enums": "A root access point of all Enum.",
	"ColorSequenceKeypoint": "A color and time value that represents a keypoint in a ColorSequence.",
	"Color3": "A color value comprised of red, green, and blue components.",
	"CatalogSearchParams": "Stores parameters used in catalog searches via AvatarEditorService:SearchCatalogAsync().",
	"Faces": "A data type containing six booleans, each representing a face of a BasePart.",
	"ColorSequence": "A gradient of color values comprised of ColorSequenceKeypoint.",
	"DateTime": "A data type that represents a moment in time.",
	"EnumItem": "An individual item in an enum.",
	"CFrame": "A data type that represents both a 3D position and orientation.",
	"BrickColor": "A data type that provides a predefined list of named colors.",
	"FloatCurveKey": "A time-value pair used with FloatCurve instances.",
	"NumberSequenceKeypoint": "Represents keypoint within a NumberSequence with a particular time, value, and envelope size.",
	"Font": "Describes the font used to render text.",
	"PhysicalProperties": "Describes properties that affect the physical behavior of a BasePart.",
	"RaycastParams": "A container for parameters used in raycasting operations.",
	"Instance": "Holds the constructor for Instances.",
	"NumberRange": "Represents a range of numbers.",
	"OverlapParams": "Stores parameters used in boundary-querying functions.",
	"RBXScriptConnection": "A connection between an RBXScriptSignal and a function.",
	"Ray": "Represents a line with a starting point that casts infinitely in a specific direction.",
	"NumberSequence": "A series of floats across a period of time.",
	"PathWaypoint": "A description of the steps required to reach the next waypoint in a path.",
	"Path2DControlPoint": "Stores the info for a single control point used with the Path2D instance.",
	"Random": "Generates pseudorandom numbers and directions.",
	"RBXScriptSignal": "An object that runs connected functions upon a specific occurrence.",
	"RaycastResult": "Stores results from a raycast operation.",
	"Rect": "A value that represents a two-dimensional rectangle.",
	"UDim2": "Represents a two-dimensional value where each dimension is composed of a relative scale and an absolute offset.",
	"Region3": "Describes a rectangular volume in 3D space.",
	"Secret": "Stores secret non-printable content.",
	"Region3int16": "Represents a Region3 stored as two boundaries as opposed to position and size components.",
	"Vector2": "Represents a 2D value with direction and magnitude.",
	"ValueCurveKey": "A time-value pair used with ValueCurve instances.",
	"UDim": "Represents a one-dimensional value with two components, a relative scale and an absolute offset.",
	"Vector3": "Represents a 3D value with a direction and magnitude.",
	"SecurityCapabilities": "A set of SecurityCapability items.",
	"SharedTable": "Provides sharable, table-like storage for key/value pairs.",
	"Vector2int16": "Represents a Vector2 with signed 16-bit integers for components.",
	"User": "Represents a user's domain-scoped identity within a specific domain.",
	"TweenInfo": "Stores parameters for Tween.",
	"Vector3int16": "A Vector3 with signed 16-bit integers for components.",
	"RotationCurveKey": "A time-value pair used with RotationCurve instances."
};
