/**
 * The methods a Roblox service has, generated into `src/core/robloxMembers.ts`.
 *
 * `scripts/build-roblox.mjs` takes the engine's *vocabulary* from a local export
 * of the Creator Hub — names and inheritance, nothing else. This takes the part
 * a name alone cannot give: what a service can be asked to do, what the call
 * takes, and what it gives back.
 *
 * ## Why the source is the docs repository
 *
 * `Roblox/creator-docs` is the reference the Creator Hub renders, in YAML, one
 * file per class, published by Roblox and regenerated with every engine release.
 * A saved page of a class would do as well, but there are forty-odd services and
 * nobody is going to save forty-odd pages by hand each time the engine moves.
 *
 * It is fetched rather than vendored, and the **result is committed**: a build of
 * Roswaal never touches the network, and updating the catalogue is a deliberate
 * `npm run build:members` whose diff is there to be read.
 *
 * Inherited methods come too, up to but not including `Instance` — `Workspace`
 * gets `Raycast` from `WorldRoot`, which is the method people actually want from
 * it. `Instance` stops the walk because its own methods (`FindFirstChild`,
 * `Destroy`, `WaitForChild`) have nodes already, and one call offered twice in
 * two shapes is a worse menu than one call offered once.
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { ROBLOX_SERVICES } from "../src/core/roblox.ts";
import { CLASS_PARENTS, ENUMS } from "../src/core/robloxData.ts";
import { methodsOf, parseYaml } from "./lib/creatorDocs.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BASE =
	"https://raw.githubusercontent.com/Roblox/creator-docs/main/content/en-us/reference/engine/classes";

/** Where the walk up the inheritance chain stops. See the header. */
const STOP_AT = new Set(["Instance", "Object", ""]);

const enums = new Set(ENUMS);
const isEnum = (name) => enums.has(name);

const cache = new Map();

async function classDoc(name) {
	if (!cache.has(name)) {
		const response = await fetch(`${BASE}/${encodeURIComponent(name)}.yaml`);
		cache.set(name, response.ok ? parseYaml(await response.text()) : null);
	}
	return cache.get(name);
}

/** The class and every ancestor of it that is not `Instance` or above. */
function chainOf(name) {
	const chain = [];
	let current = name;
	while (current && !STOP_AT.has(current) && !chain.includes(current)) {
		chain.push(current);
		current = CLASS_PARENTS[current];
	}
	return chain;
}

const services = {};
const missing = [];

for (const service of ROBLOX_SERVICES) {
	const methods = [];
	const seen = new Set();
	for (const className of chainOf(service)) {
		const doc = await classDoc(className);
		if (!doc) {
			if (className === service) missing.push(service);
			continue;
		}
		// The walk starts at the service itself, so an override wins over the
		// declaration it overrides.
		for (const method of methodsOf(doc, className, isEnum)) {
			if (seen.has(method.name)) continue;
			seen.add(method.name);
			methods.push(method);
		}
	}
	methods.sort((a, b) => a.name.localeCompare(b.name));
	if (methods.length > 0) services[service] = methods;
}

const json = (value) => JSON.stringify(value);

const header = `/**
 * What a Roblox service can be asked to do.
 *
 * Generated by \`scripts/build-members.mjs\` from Roblox's own documentation
 * repository — do not edit by hand. Methods a game script cannot call are not
 * here: anything behind a security context, and anything deprecated.
 *
 * Inherited methods are included up to but not including \`Instance\`, whose own
 * methods have nodes of their own.
 *
 * Like every other generated list this is a **suggestion rather than a gate**:
 * the method name is a dropdown you can type past, so a method newer than this
 * build still compiles.
 *
 * The summaries are text from Roblox's Creator Documentation
 * (https://github.com/Roblox/creator-docs), (c) Roblox Corporation, used under
 * CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/), each shortened to
 * its first sentence with its markup removed. They are not covered by
 * Roswaal's 0BSD licence; see ATTRIBUTIONS.md.
 */

/** One argument of a service method. */
export interface MethodParam {
	name: string;
	/** A Roswaal pin type. \`""\` where the engine documents no type. */
	type: string;
	/** Set when the argument is an enum value: the enum it belongs to. */
	enum?: string;
	/** Documented with a default, so the call may leave it out. */
	optional?: true;
	summary?: string;
}

/** One method of a service. */
export interface ServiceMethod {
	name: string;
	/** The class it is declared on, which may be an ancestor of the service. */
	from: string;
	summary: string;
	params: readonly MethodParam[];
	/** The first return type, or \`""\` for a method that returns nothing. */
	returns: string;
	/** Yields: the thread stops here until the engine comes back. */
	yields?: true;
	/**
	 * Reads rather than does, so the menu offers it as a pure node.
	 *
	 * A judgement from the name and the signature rather than something the
	 * engine states — see \`looksPure\`. Either node calls any method, so a wrong
	 * guess costs a swap rather than a miscompile.
	 */
	pure?: true;
}

/** Every service that has methods of its own, by name. */
export const SERVICE_METHODS: Readonly<Record<string, readonly ServiceMethod[]>> = {`;

const lines = [header];

for (const [service, methods] of Object.entries(services)) {
	lines.push(`\t${service}: [`);
	for (const method of methods) {
		const parts = [
			`name: ${json(method.name)}`,
			`from: ${json(method.from)}`,
			`summary: ${json(method.summary)}`,
			`params: [${method.params
				.map((p) => {
					const bits = [`name: ${json(p.name)}`, `type: ${json(p.type)}`];
					if (p.enum) bits.push(`enum: ${json(p.enum)}`);
					if (p.optional) bits.push("optional: true");
					if (p.summary) bits.push(`summary: ${json(p.summary)}`);
					return `{ ${bits.join(", ")} }`;
				})
				.join(", ")}]`,
			`returns: ${json(method.returns)}`,
		];
		if (method.yields) parts.push("yields: true");
		if (method.pure) parts.push("pure: true");
		lines.push(`\t\t{ ${parts.join(", ")} },`);
	}
	lines.push(`\t],`);
}

lines.push("};", "");

await writeFile(join(ROOT, "src/core/robloxMembers.ts"), lines.join("\n"), "utf8");

const count = Object.values(services).reduce((n, list) => n + list.length, 0);
const pure = Object.values(services).reduce((n, list) => n + list.filter((m) => m.pure).length, 0);
console.log(`${Object.keys(services).length} services, ${count} methods (${pure} read-only)`);
if (missing.length > 0) console.log(`no page for: ${missing.join(", ")}`);
