/**
 * Where the demo graphs' nodes sit, taken from the project.
 *
 * Generated by `scripts/fold-demo-layout.mjs` — do not edit by hand. The
 * placement in `demos.ts` says which column a node belongs in, which is the
 * right way to *author* a graph and a poor way to finish one; this is the
 * arrangement somebody made in the editor, which is what the page draws.
 *
 * Keyed by the demo's slug, then by node id.
 */
export const DEMO_LAYOUT: Record<string, Record<string, { x: number; y: number }>> = {
	"count-characters": {
		n0: { x: 0, y: 0 },
		n1: { x: 4, y: 105 },
		n2: { x: 297, y: 121 },
		n3: { x: 609, y: 97 },
		n4: { x: 940, y: 0 },
	},
	"fetch-json": {
		n0: { x: 0, y: 0 },
		n1: { x: 348, y: -16 },
		n2: { x: 646, y: 216 },
		n3: { x: 925, y: 176 },
		n4: { x: 1204, y: 192 },
		n5: { x: 1513, y: 168 },
		n6: { x: 1848, y: 0 },
	},
	"walk-a-directory": {
		n0: { x: 0, y: 0 },
		n1: { x: 0, y: 96 },
		n2: { x: 360, y: 0 },
		n3: { x: 672, y: 56 },
		n4: { x: 940, y: 0 },
		n5: { x: 672, y: 192 },
		n6: { x: 1410, y: 0 },
		n7: { x: 672, y: 332 },
		n8: { x: 1410, y: 140 },
	},
	"greet": {
		n0: { x: 0, y: -9 },
		n1: { x: 0, y: 92 },
		n2: { x: 336, y: 92 },
		n3: { x: 696, y: 120 },
		n4: { x: 840, y: -9 },
		n5: { x: 1172, y: -9 },
		n6: { x: 1536, y: -25 },
		n7: { x: 269, y: 264 },
		n8: { x: 504, y: 240 },
		n9: { x: 1176, y: 144 },
	},
};
