/**
 * The Roblox demo project's graphs and its node map, as data.
 *
 * Generated by `scripts/build-roblox-demos.mjs` — do not edit by hand. These
 * are the files in `examples/demo`, which is the project the panel offers to
 * take a copy of: what the page shows and what the copy contains are the same
 * thing, and they would not stay that way if this were kept by hand.
 *
 * Cast rather than annotated, because these are JSON: every string in them
 * widens away from the literal types the schema's unions are built on. What
 * checks them is behaviour — `tests/robloxdemos.test.ts` compiles them and
 * compares them against the files on disk.
 */

import type { NodeMap } from "../nodemap.js";
import type { NodeScript } from "../schema.js";

/** Keyed by the name the page uses, not by the path on disk. */
export const ROBLOX_DEMO_GRAPHS =
	{
		"greeter": {
			"schemaVersion": 1,
			"kind": "script",
			"id": "demo-greeter",
			"name": "Greeter",
			"scriptClass": "ModuleScript",
			"target": "roblox",
			"typecheck": "strict",
			"variables": [
				{
					"id": "29751969-1b75-45e4-902e-01a6804c8284",
					"name": "Accumulator",
					"type": "number",
					"default": {
						"t": "number",
						"v": 0
					}
				}
			],
			"nodes": [
				{
					"id": "091a4b93-e238-446a-a258-c4fd3407507e",
					"def": "math.add",
					"x": 387,
					"y": -37,
					"graph": "a17d2f2d-90fc-4ad7-8260-2302e0aad281"
				},
				{
					"id": "18e9cab5-80cf-4814-8997-9e445a7795ae",
					"def": "function.get",
					"x": 130,
					"y": -461,
					"config": {
						"function": "a17d2f2d-90fc-4ad7-8260-2302e0aad281",
						"name": "AccumulateNum"
					}
				},
				{
					"id": "1ad858dd-cb06-42e8-bb0c-71e44113e704",
					"def": "function.get",
					"x": 138.44,
					"y": -517.09,
					"config": {
						"function": "fn",
						"name": "GreetPlayer"
					}
				},
				{
					"id": "2d5f6dbe-0ae5-49ad-bfb6-a4cb624995ae",
					"def": "function.return",
					"x": 1030,
					"y": -197,
					"config": {
						"returns": [
							{
								"name": "Accumulated",
								"type": "number"
							}
						]
					},
					"graph": "a17d2f2d-90fc-4ad7-8260-2302e0aad281"
				},
				{
					"id": "9f7806fd-3992-4c4f-8e8b-73eb443b9782",
					"def": "variable.set",
					"x": 724,
					"y": -213,
					"config": {
						"name": "Accumulator",
						"type": "number",
						"variable": "29751969-1b75-45e4-902e-01a6804c8284"
					},
					"graph": "a17d2f2d-90fc-4ad7-8260-2302e0aad281"
				},
				{
					"id": "a0e48503-7ed3-4988-a0a1-c7f15666bbb2",
					"def": "variable.get",
					"x": 175,
					"y": 15,
					"config": {
						"name": "Accumulator",
						"type": "number",
						"variable": "29751969-1b75-45e4-902e-01a6804c8284"
					},
					"graph": "a17d2f2d-90fc-4ad7-8260-2302e0aad281"
				},
				{
					"id": "a17d2f2d-90fc-4ad7-8260-2302e0aad281",
					"def": "function.entry",
					"x": 112,
					"y": -213,
					"config": {
						"name": "AccumulateNum",
						"params": [
							{
								"name": "A",
								"type": "number"
							}
						],
						"returns": [
							{
								"name": "value1",
								"type": "number"
							}
						]
					}
				},
				{
					"id": "concat",
					"def": "string.concat",
					"x": 400,
					"y": 300,
					"literals": {
						"a0": {
							"t": "string",
							"v": "Hello, "
						}
					},
					"graph": "fn"
				},
				{
					"id": "exports",
					"def": "module.exports",
					"x": 344,
					"y": -533,
					"config": {
						"exports": [
							{
								"name": "greet",
								"type": "function"
							},
							{
								"name": "export2",
								"type": "function"
							}
						]
					}
				},
				{
					"id": "fn",
					"def": "function.entry",
					"x": 95,
					"y": 127,
					"config": {
						"name": "GreetPlayer",
						"params": [
							{
								"name": "who",
								"type": "string"
							}
						],
						"returns": [
							{
								"name": "message",
								"type": "string"
							}
						]
					}
				},
				{
					"id": "ret",
					"def": "function.return",
					"x": 700,
					"y": 140,
					"config": {
						"returns": [
							{
								"name": "message",
								"type": "string"
							}
						]
					},
					"graph": "fn"
				}
			],
			"links": [
				{
					"id": "11243744-db4a-45b3-bc82-622235c85eb8",
					"from": {
						"node": "a17d2f2d-90fc-4ad7-8260-2302e0aad281",
						"pin": "p0"
					},
					"to": {
						"node": "091a4b93-e238-446a-a258-c4fd3407507e",
						"pin": "a0"
					}
				},
				{
					"id": "4c022a62-75b1-4599-87ff-d557c68bc7a1",
					"from": {
						"node": "a0e48503-7ed3-4988-a0a1-c7f15666bbb2",
						"pin": "value"
					},
					"to": {
						"node": "091a4b93-e238-446a-a258-c4fd3407507e",
						"pin": "a1"
					}
				},
				{
					"id": "4da6ffcc-91f9-4b0a-8de3-95d3eddaf7da",
					"from": {
						"node": "9f7806fd-3992-4c4f-8e8b-73eb443b9782",
						"pin": "value"
					},
					"to": {
						"node": "2d5f6dbe-0ae5-49ad-bfb6-a4cb624995ae",
						"pin": "r0"
					}
				},
				{
					"id": "ae19f7d7-90cf-4fb2-9516-2ba19411902f",
					"from": {
						"node": "9f7806fd-3992-4c4f-8e8b-73eb443b9782",
						"pin": "then"
					},
					"to": {
						"node": "2d5f6dbe-0ae5-49ad-bfb6-a4cb624995ae",
						"pin": "in"
					}
				},
				{
					"id": "d278e4d8-6785-4330-bcb1-ee1d356ac769",
					"from": {
						"node": "091a4b93-e238-446a-a258-c4fd3407507e",
						"pin": "result"
					},
					"to": {
						"node": "9f7806fd-3992-4c4f-8e8b-73eb443b9782",
						"pin": "value"
					}
				},
				{
					"id": "dc8beb62-f7d0-400d-8a18-406015c9a6c9",
					"from": {
						"node": "1ad858dd-cb06-42e8-bb0c-71e44113e704",
						"pin": "fn"
					},
					"to": {
						"node": "exports",
						"pin": "e0"
					}
				},
				{
					"id": "ec81dfa5-cf7d-4a35-9515-d156d0292ab0",
					"from": {
						"node": "a17d2f2d-90fc-4ad7-8260-2302e0aad281",
						"pin": "then"
					},
					"to": {
						"node": "9f7806fd-3992-4c4f-8e8b-73eb443b9782",
						"pin": "in"
					}
				},
				{
					"id": "fbad443f-7e67-41d6-bbf0-1688d234d201",
					"from": {
						"node": "18e9cab5-80cf-4814-8997-9e445a7795ae",
						"pin": "fn"
					},
					"to": {
						"node": "exports",
						"pin": "e1"
					}
				},
				{
					"id": "g1",
					"from": {
						"node": "fn",
						"pin": "then"
					},
					"to": {
						"node": "ret",
						"pin": "in"
					}
				},
				{
					"id": "g2",
					"from": {
						"node": "fn",
						"pin": "p0"
					},
					"to": {
						"node": "concat",
						"pin": "a1"
					}
				},
				{
					"id": "g3",
					"from": {
						"node": "concat",
						"pin": "result"
					},
					"to": {
						"node": "ret",
						"pin": "r0"
					}
				}
			],
			"comments": []
		},
		"main": {
			"schemaVersion": 1,
			"kind": "script",
			"id": "demo-main",
			"name": "Main",
			"scriptClass": "Script",
			"target": "roblox",
			"typecheck": "strict",
			"variables": [
				{
					"id": "v-joined",
					"name": "playersJoined",
					"type": "number",
					"default": {
						"t": "number",
						"v": 0
					},
					"description": "How many players have joined since the server started."
				}
			],
			"nodes": [
				{
					"id": "13a5c553-604c-4034-a094-9f63467069db",
					"def": "flow.sequence",
					"x": 72,
					"y": 192
				},
				{
					"id": "1b0880ee-a507-41d2-a9e3-fa722b301ee8",
					"def": "code.custom",
					"x": 539,
					"y": 840,
					"literals": {
						"code": {
							"t": "raw",
							"v": "newPart.Material = Enum.Material.Neon"
						}
					}
				},
				{
					"id": "4e360814-1d98-41d1-ae9c-7c7168805c5b",
					"def": "code.custom",
					"x": 233,
					"y": 840,
					"literals": {
						"code": {
							"t": "raw",
							"v": "\n-- your Luau here\n\nprint(\"This is from a custom code block.\")\n\nlocal newPart = Instance.new(\"Part\")\nnewPart.Parent = workspace\nnewPart.Anchored = true\nnewPart.Size = Vector3.new(5, 5, 5)\n\nnewPart.Position = Vector3.new(10, 5, 10)"
						}
					}
				},
				{
					"id": "a520f24f-70db-43a6-81f3-2c86ff7bce8d",
					"def": "flow.rerouteExec",
					"x": 121,
					"y": 871
				},
				{
					"id": "conn",
					"def": "event.connect",
					"x": 638.61,
					"y": 198.61,
					"config": {
						"params": [
							{
								"name": "player",
								"type": "Instance"
							}
						]
					}
				},
				{
					"id": "count",
					"def": "variable.get",
					"x": 1463,
					"y": 384,
					"config": {
						"name": "playersJoined",
						"type": "number",
						"variable": "v-joined"
					}
				},
				{
					"id": "countUp",
					"def": "variable.set",
					"x": 1966,
					"y": 229,
					"config": {
						"name": "playersJoined",
						"type": "number",
						"variable": "v-joined"
					}
				},
				{
					"id": "greet",
					"def": "call.function",
					"x": 1277,
					"y": 240,
					"config": {
						"args": 1
					}
				},
				{
					"id": "greeterModule",
					"def": "module.requirePath",
					"x": 660,
					"y": 484,
					"literals": {
						"as": {
							"t": "string",
							"v": "Greeter"
						},
						"path": {
							"t": "string",
							"v": "Shared.Greeter"
						},
						"root": {
							"t": "string",
							"v": "ReplicatedStorage"
						}
					}
				},
				{
					"id": "greetFn",
					"def": "value.field",
					"x": 956,
					"y": 483,
					"literals": {
						"field": {
							"t": "string",
							"v": "greet"
						}
					}
				},
				{
					"id": "increment",
					"def": "math.add",
					"x": 1671,
					"y": 355,
					"literals": {
						"a1": {
							"t": "number",
							"v": 1
						}
					}
				},
				{
					"id": "pname",
					"def": "roblox.getProperty",
					"x": 921,
					"y": 303,
					"literals": {
						"property": {
							"t": "string",
							"v": "Name"
						}
					}
				},
				{
					"id": "say",
					"def": "debug.print",
					"x": 1671,
					"y": 247
				},
				{
					"id": "signal",
					"def": "roblox.getEvent",
					"x": -11,
					"y": 396,
					"literals": {
						"event": {
							"t": "string",
							"v": "PlayerAdded"
						}
					}
				},
				{
					"id": "start",
					"def": "script.begin",
					"x": -336,
					"y": 192
				},
				{
					"id": "svc",
					"def": "roblox.getService",
					"x": -303,
					"y": 396,
					"literals": {
						"service": {
							"t": "string",
							"v": "Players"
						}
					}
				}
			],
			"links": [
				{
					"id": "15d6c93c-7a5a-471a-9659-2dff43476f6f",
					"from": {
						"node": "13a5c553-604c-4034-a094-9f63467069db",
						"pin": "s1"
					},
					"to": {
						"node": "a520f24f-70db-43a6-81f3-2c86ff7bce8d",
						"pin": "in"
					}
				},
				{
					"id": "20459c65-a0ca-4571-aded-a8e54aedf188",
					"from": {
						"node": "13a5c553-604c-4034-a094-9f63467069db",
						"pin": "s0"
					},
					"to": {
						"node": "conn",
						"pin": "in"
					}
				},
				{
					"id": "5a9fcf20-45d2-4351-acb3-ca93b842ac1d",
					"from": {
						"node": "4e360814-1d98-41d1-ae9c-7c7168805c5b",
						"pin": "then"
					},
					"to": {
						"node": "1b0880ee-a507-41d2-a9e3-fa722b301ee8",
						"pin": "in"
					}
				},
				{
					"id": "66f01859-b37d-4966-88f4-3c3068d89cc1",
					"from": {
						"node": "a520f24f-70db-43a6-81f3-2c86ff7bce8d",
						"pin": "then"
					},
					"to": {
						"node": "4e360814-1d98-41d1-ae9c-7c7168805c5b",
						"pin": "in"
					}
				},
				{
					"id": "cce0ba09-991c-49ef-8839-212985373b35",
					"from": {
						"node": "start",
						"pin": "then"
					},
					"to": {
						"node": "13a5c553-604c-4034-a094-9f63467069db",
						"pin": "in"
					}
				},
				{
					"id": "l10",
					"from": {
						"node": "greet",
						"pin": "result"
					},
					"to": {
						"node": "say",
						"pin": "value"
					}
				},
				{
					"id": "l11",
					"from": {
						"node": "say",
						"pin": "then"
					},
					"to": {
						"node": "countUp",
						"pin": "in"
					}
				},
				{
					"id": "l12",
					"from": {
						"node": "count",
						"pin": "value"
					},
					"to": {
						"node": "increment",
						"pin": "a0"
					}
				},
				{
					"id": "l13",
					"from": {
						"node": "increment",
						"pin": "result"
					},
					"to": {
						"node": "countUp",
						"pin": "value"
					}
				},
				{
					"id": "l2",
					"from": {
						"node": "svc",
						"pin": "service"
					},
					"to": {
						"node": "signal",
						"pin": "instance"
					}
				},
				{
					"id": "l3",
					"from": {
						"node": "signal",
						"pin": "result"
					},
					"to": {
						"node": "conn",
						"pin": "signal"
					}
				},
				{
					"id": "l4",
					"from": {
						"node": "conn",
						"pin": "body"
					},
					"to": {
						"node": "greet",
						"pin": "in"
					}
				},
				{
					"id": "l5",
					"from": {
						"node": "conn",
						"pin": "p0"
					},
					"to": {
						"node": "pname",
						"pin": "instance"
					}
				},
				{
					"id": "l6",
					"from": {
						"node": "greeterModule",
						"pin": "exports"
					},
					"to": {
						"node": "greetFn",
						"pin": "object"
					}
				},
				{
					"id": "l7",
					"from": {
						"node": "greetFn",
						"pin": "result"
					},
					"to": {
						"node": "greet",
						"pin": "fn"
					}
				},
				{
					"id": "l8",
					"from": {
						"node": "pname",
						"pin": "result"
					},
					"to": {
						"node": "greet",
						"pin": "a0"
					}
				},
				{
					"id": "l9",
					"from": {
						"node": "greet",
						"pin": "then"
					},
					"to": {
						"node": "say",
						"pin": "in"
					}
				}
			],
			"comments": [
				{
					"id": "c1",
					"x": 613,
					"y": 155,
					"w": 1590.4,
					"h": 520.68,
					"text": "Greet every player who joins",
					"color": "5f8f6a"
				},
				{
					"id": "c2",
					"x": 634,
					"y": 439,
					"w": 564,
					"h": 183,
					"text": "Shared module, required once at the top",
					"color": "6a8fbf"
				}
			]
		}
	} as unknown as Record<string, NodeScript>;

/** The demo's node map, drawn on the page in the editor that edits it. */
export const ROBLOX_DEMO_MAP =
	{
		"schemaVersion": 1,
		"kind": "map",
		"id": "demo-game-map",
		"name": "roswaal-demo",
		"output": "default.project.json",
		"globIgnorePaths": [
			"**/*.spec.luau"
		],
		"root": {
			"id": "root",
			"name": "DataModel",
			"className": "DataModel",
			"children": [
				{
					"id": "sss",
					"name": "ServerScriptService",
					"children": [
						{
							"id": "302d91bf-1945-4d44-9e6c-dd93fd6dfc16",
							"name": "Source",
							"className": "Folder",
							"path": "src/ServerScriptService/Source",
							"children": []
						}
					]
				},
				{
					"id": "rs",
					"name": "ReplicatedStorage",
					"children": [
						{
							"id": "00d0d6db-8c84-4043-9088-2aff7cacacc5",
							"name": "Shared",
							"className": "Folder",
							"path": "src/ReplicatedStorage/Shared",
							"children": []
						}
					]
				}
			]
		}
	} as unknown as NodeMap;
